/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelsVOIPDeviceOutputLineKey from './ModelsVOIPDeviceOutputLineKey';

/**
 * The ModelsDeviceOutputFullProvision model module.
 * @module model/ModelsDeviceOutputFullProvision
 * @version 1.1
 */
class ModelsDeviceOutputFullProvision {
    /**
     * Constructs a new <code>ModelsDeviceOutputFullProvision</code>.
     * @alias module:model/ModelsDeviceOutputFullProvision
     */
    constructor() { 
        
        ModelsDeviceOutputFullProvision.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModelsDeviceOutputFullProvision</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModelsDeviceOutputFullProvision} obj Optional instance to populate.
     * @return {module:model/ModelsDeviceOutputFullProvision} The populated <code>ModelsDeviceOutputFullProvision</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModelsDeviceOutputFullProvision();

            if (data.hasOwnProperty('endpoint_brand')) {
                obj['endpoint_brand'] = ApiClient.convertToType(data['endpoint_brand'], 'String');
            }
            if (data.hasOwnProperty('endpoint_family')) {
                obj['endpoint_family'] = ApiClient.convertToType(data['endpoint_family'], 'String');
            }
            if (data.hasOwnProperty('endpoint_model')) {
                obj['endpoint_model'] = ApiClient.convertToType(data['endpoint_model'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('line_keys')) {
                obj['line_keys'] = ApiClient.convertToType(data['line_keys'], [ModelsVOIPDeviceOutputLineKey]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModelsDeviceOutputFullProvision</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModelsDeviceOutputFullProvision</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['endpoint_brand'] && !(typeof data['endpoint_brand'] === 'string' || data['endpoint_brand'] instanceof String)) {
            throw new Error("Expected the field `endpoint_brand` to be a primitive type in the JSON string but got " + data['endpoint_brand']);
        }
        // ensure the json data is a string
        if (data['endpoint_family'] && !(typeof data['endpoint_family'] === 'string' || data['endpoint_family'] instanceof String)) {
            throw new Error("Expected the field `endpoint_family` to be a primitive type in the JSON string but got " + data['endpoint_family']);
        }
        // ensure the json data is a string
        if (data['endpoint_model'] && !(typeof data['endpoint_model'] === 'string' || data['endpoint_model'] instanceof String)) {
            throw new Error("Expected the field `endpoint_model` to be a primitive type in the JSON string but got " + data['endpoint_model']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['line_keys']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['line_keys'])) {
                throw new Error("Expected the field `line_keys` to be an array in the JSON data but got " + data['line_keys']);
            }
            // validate the optional field `line_keys` (array)
            for (const item of data['line_keys']) {
                ModelsVOIPDeviceOutputLineKey.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {String} endpoint_brand
 */
ModelsDeviceOutputFullProvision.prototype['endpoint_brand'] = undefined;

/**
 * @member {String} endpoint_family
 */
ModelsDeviceOutputFullProvision.prototype['endpoint_family'] = undefined;

/**
 * @member {String} endpoint_model
 */
ModelsDeviceOutputFullProvision.prototype['endpoint_model'] = undefined;

/**
 * @member {String} id
 */
ModelsDeviceOutputFullProvision.prototype['id'] = undefined;

/**
 * @member {Array.<module:model/ModelsVOIPDeviceOutputLineKey>} line_keys
 */
ModelsDeviceOutputFullProvision.prototype['line_keys'] = undefined;






export default ModelsDeviceOutputFullProvision;

