/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import ModelMonthlySummaryComponentsData;

/**
 * ModelMonthlySummaryReport
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ModelMonthlySummaryReport {
  @.annotation.Nullable
  private [ModelMonthlySummaryComponentsData] components;

  @.annotation.Nullable
  private Number transactionMonth;

  @.annotation.Nullable
  private Number transactionYear;

  public ModelMonthlySummaryReport() {
  }

  public ModelMonthlySummaryReport components(@.annotation.Nullable [ModelMonthlySummaryComponentsData] components) {
    
    this.components = components;
    return this;
  }

  public ModelMonthlySummaryReport addComponentsItem(ModelMonthlySummaryComponentsData componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

  /**
   * Get components
   * @return components
   */
  @.annotation.Nullable

  public [ModelMonthlySummaryComponentsData] getComponents() {
    return components;
  }


  public void setComponents(@.annotation.Nullable [ModelMonthlySummaryComponentsData] components) {
    this.components = components;
  }

  public ModelMonthlySummaryReport transactionMonth(@.annotation.Nullable Number transactionMonth) {
    
    this.transactionMonth = transactionMonth;
    return this;
  }

  /**
   * Get transactionMonth
   * @return transactionMonth
   */
  @.annotation.Nullable

  public Number getTransactionMonth() {
    return transactionMonth;
  }


  public void setTransactionMonth(@.annotation.Nullable Number transactionMonth) {
    this.transactionMonth = transactionMonth;
  }

  public ModelMonthlySummaryReport transactionYear(@.annotation.Nullable Number transactionYear) {
    
    this.transactionYear = transactionYear;
    return this;
  }

  /**
   * Get transactionYear
   * @return transactionYear
   */
  @.annotation.Nullable

  public Number getTransactionYear() {
    return transactionYear;
  }


  public void setTransactionYear(@.annotation.Nullable Number transactionYear) {
    this.transactionYear = transactionYear;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelMonthlySummaryReport modelMonthlySummaryReport = (ModelMonthlySummaryReport) o;
    return Objects.equals(this.components, modelMonthlySummaryReport.components) &&
        Objects.equals(this.transactionMonth, modelMonthlySummaryReport.transactionMonth) &&
        Objects.equals(this.transactionYear, modelMonthlySummaryReport.transactionYear);
  }

  @Override
  public int hashCode() {
    return Objects.hash(components, transactionMonth, transactionYear);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelMonthlySummaryReport {\n");
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    transactionMonth: ").append(toIndentedString(transactionMonth)).append("\n");
    sb.append("    transactionYear: ").append(toIndentedString(transactionYear)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

