/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceVOIPTemporalRuleSetAddEditData
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVOIPTemporalRuleSetAddEditData {
  @.annotation.Nonnull
  private String name;

  @.annotation.Nullable
  private [String] temporalRules;

  public ServiceVOIPTemporalRuleSetAddEditData() {
  }

  public ServiceVOIPTemporalRuleSetAddEditData name(@.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @.annotation.Nonnull

  public String getName() {
    return name;
  }


  public void setName(@.annotation.Nonnull String name) {
    this.name = name;
  }

  public ServiceVOIPTemporalRuleSetAddEditData temporalRules(@.annotation.Nullable [String] temporalRules) {
    
    this.temporalRules = temporalRules;
    return this;
  }

  public ServiceVOIPTemporalRuleSetAddEditData addTemporalRulesItem(String temporalRulesItem) {
    if (this.temporalRules == null) {
      this.temporalRules = new ArrayList<>();
    }
    this.temporalRules.add(temporalRulesItem);
    return this;
  }

  /**
   * Get temporalRules
   * @return temporalRules
   */
  @.annotation.Nullable

  public [String] getTemporalRules() {
    return temporalRules;
  }


  public void setTemporalRules(@.annotation.Nullable [String] temporalRules) {
    this.temporalRules = temporalRules;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPTemporalRuleSetAddEditData serviceVOIPTemporalRuleSetAddEditData = (ServiceVOIPTemporalRuleSetAddEditData) o;
    return Objects.equals(this.name, serviceVOIPTemporalRuleSetAddEditData.name) &&
        Objects.equals(this.temporalRules, serviceVOIPTemporalRuleSetAddEditData.temporalRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, temporalRules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPTemporalRuleSetAddEditData {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    temporalRules: ").append(toIndentedString(temporalRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

