/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceE911LocationInput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceE911LocationInput {
  @.annotation.Nonnull
  private String address1;

  @.annotation.Nullable
  private String address2;

  @.annotation.Nonnull
  private String community;

  @.annotation.Nullable
  private String plusFour;

  @.annotation.Nonnull
  private String postalCode;

  @.annotation.Nonnull
  private String state;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    ADDRESS(String.valueOf("ADDRESS"));

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @.annotation.Nullable
  private TypeEnum type;

  public ServiceE911LocationInput() {
  }

  public ServiceE911LocationInput address1(@.annotation.Nonnull String address1) {
    
    this.address1 = address1;
    return this;
  }

  /**
   * Get address1
   * @return address1
   */
  @.annotation.Nonnull

  public String getAddress1() {
    return address1;
  }


  public void setAddress1(@.annotation.Nonnull String address1) {
    this.address1 = address1;
  }

  public ServiceE911LocationInput address2(@.annotation.Nullable String address2) {
    
    this.address2 = address2;
    return this;
  }

  /**
   * Get address2
   * @return address2
   */
  @.annotation.Nullable

  public String getAddress2() {
    return address2;
  }


  public void setAddress2(@.annotation.Nullable String address2) {
    this.address2 = address2;
  }

  public ServiceE911LocationInput community(@.annotation.Nonnull String community) {
    
    this.community = community;
    return this;
  }

  /**
   * Get community
   * @return community
   */
  @.annotation.Nonnull

  public String getCommunity() {
    return community;
  }


  public void setCommunity(@.annotation.Nonnull String community) {
    this.community = community;
  }

  public ServiceE911LocationInput plusFour(@.annotation.Nullable String plusFour) {
    
    this.plusFour = plusFour;
    return this;
  }

  /**
   * Get plusFour
   * @return plusFour
   */
  @.annotation.Nullable

  public String getPlusFour() {
    return plusFour;
  }


  public void setPlusFour(@.annotation.Nullable String plusFour) {
    this.plusFour = plusFour;
  }

  public ServiceE911LocationInput postalCode(@.annotation.Nonnull String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

  /**
   * Get postalCode
   * @return postalCode
   */
  @.annotation.Nonnull

  public String getPostalCode() {
    return postalCode;
  }


  public void setPostalCode(@.annotation.Nonnull String postalCode) {
    this.postalCode = postalCode;
  }

  public ServiceE911LocationInput state(@.annotation.Nonnull String state) {
    
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @.annotation.Nonnull

  public String getState() {
    return state;
  }


  public void setState(@.annotation.Nonnull String state) {
    this.state = state;
  }

  public ServiceE911LocationInput type(@.annotation.Nullable TypeEnum type) {
    
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @.annotation.Nullable

  public TypeEnum getType() {
    return type;
  }


  public void setType(@.annotation.Nullable TypeEnum type) {
    this.type = type;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceE911LocationInput serviceE911LocationInput = (ServiceE911LocationInput) o;
    return Objects.equals(this.address1, serviceE911LocationInput.address1) &&
        Objects.equals(this.address2, serviceE911LocationInput.address2) &&
        Objects.equals(this.community, serviceE911LocationInput.community) &&
        Objects.equals(this.plusFour, serviceE911LocationInput.plusFour) &&
        Objects.equals(this.postalCode, serviceE911LocationInput.postalCode) &&
        Objects.equals(this.state, serviceE911LocationInput.state) &&
        Objects.equals(this.type, serviceE911LocationInput.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address1, address2, community, plusFour, postalCode, state, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceE911LocationInput {\n");
    sb.append("    address1: ").append(toIndentedString(address1)).append("\n");
    sb.append("    address2: ").append(toIndentedString(address2)).append("\n");
    sb.append("    community: ").append(toIndentedString(community)).append("\n");
    sb.append("    plusFour: ").append(toIndentedString(plusFour)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

