/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import ServiceSystemStatusCPAASService;
import ServiceSystemStatusMessagingService;
import ServiceSystemStatusSupportService;
import ServiceSystemStatusVOIPService;

/**
 * ServiceSystemStatusOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceSystemStatusOutput {
  @.annotation.Nullable
  private ServiceSystemStatusCPAASService cpaasServices;

  @.annotation.Nullable
  private ServiceSystemStatusMessagingService messagingServices;

  @.annotation.Nullable
  private ServiceSystemStatusSupportService supportServices;

  @.annotation.Nullable
  private ServiceSystemStatusVOIPService voipServices;

  public ServiceSystemStatusOutput() {
  }

  public ServiceSystemStatusOutput cpaasServices(@.annotation.Nullable ServiceSystemStatusCPAASService cpaasServices) {
    
    this.cpaasServices = cpaasServices;
    return this;
  }

  /**
   * Get cpaasServices
   * @return cpaasServices
   */
  @.annotation.Nullable

  public ServiceSystemStatusCPAASService getCpaasServices() {
    return cpaasServices;
  }


  public void setCpaasServices(@.annotation.Nullable ServiceSystemStatusCPAASService cpaasServices) {
    this.cpaasServices = cpaasServices;
  }

  public ServiceSystemStatusOutput messagingServices(@.annotation.Nullable ServiceSystemStatusMessagingService messagingServices) {
    
    this.messagingServices = messagingServices;
    return this;
  }

  /**
   * Get messagingServices
   * @return messagingServices
   */
  @.annotation.Nullable

  public ServiceSystemStatusMessagingService getMessagingServices() {
    return messagingServices;
  }


  public void setMessagingServices(@.annotation.Nullable ServiceSystemStatusMessagingService messagingServices) {
    this.messagingServices = messagingServices;
  }

  public ServiceSystemStatusOutput supportServices(@.annotation.Nullable ServiceSystemStatusSupportService supportServices) {
    
    this.supportServices = supportServices;
    return this;
  }

  /**
   * Get supportServices
   * @return supportServices
   */
  @.annotation.Nullable

  public ServiceSystemStatusSupportService getSupportServices() {
    return supportServices;
  }


  public void setSupportServices(@.annotation.Nullable ServiceSystemStatusSupportService supportServices) {
    this.supportServices = supportServices;
  }

  public ServiceSystemStatusOutput voipServices(@.annotation.Nullable ServiceSystemStatusVOIPService voipServices) {
    
    this.voipServices = voipServices;
    return this;
  }

  /**
   * Get voipServices
   * @return voipServices
   */
  @.annotation.Nullable

  public ServiceSystemStatusVOIPService getVoipServices() {
    return voipServices;
  }


  public void setVoipServices(@.annotation.Nullable ServiceSystemStatusVOIPService voipServices) {
    this.voipServices = voipServices;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceSystemStatusOutput serviceSystemStatusOutput = (ServiceSystemStatusOutput) o;
    return Objects.equals(this.cpaasServices, serviceSystemStatusOutput.cpaasServices) &&
        Objects.equals(this.messagingServices, serviceSystemStatusOutput.messagingServices) &&
        Objects.equals(this.supportServices, serviceSystemStatusOutput.supportServices) &&
        Objects.equals(this.voipServices, serviceSystemStatusOutput.voipServices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cpaasServices, messagingServices, supportServices, voipServices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceSystemStatusOutput {\n");
    sb.append("    cpaasServices: ").append(toIndentedString(cpaasServices)).append("\n");
    sb.append("    messagingServices: ").append(toIndentedString(messagingServices)).append("\n");
    sb.append("    supportServices: ").append(toIndentedString(supportServices)).append("\n");
    sb.append("    voipServices: ").append(toIndentedString(voipServices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

