/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceE911LocationURIStatus
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceE911LocationURIStatus {
  @.annotation.Nullable
  private String code;

  @.annotation.Nullable
  private String description;

  public ServiceE911LocationURIStatus() {
  }

  public ServiceE911LocationURIStatus code(@.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }

  /**
   * Get code
   * @return code
   */
  @.annotation.Nullable

  public String getCode() {
    return code;
  }


  public void setCode(@.annotation.Nullable String code) {
    this.code = code;
  }

  public ServiceE911LocationURIStatus description(@.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@.annotation.Nullable String description) {
    this.description = description;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceE911LocationURIStatus serviceE911LocationURIStatus = (ServiceE911LocationURIStatus) o;
    return Objects.equals(this.code, serviceE911LocationURIStatus.code) &&
        Objects.equals(this.description, serviceE911LocationURIStatus.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, description);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceE911LocationURIStatus {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

