/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServicePhoneNumberSearchOutput model module.
 * @module model/ServicePhoneNumberSearchOutput
 * @version 1.1
 */
class ServicePhoneNumberSearchOutput {
    /**
     * Constructs a new <code>ServicePhoneNumberSearchOutput</code>.
     * @alias module:model/ServicePhoneNumberSearchOutput
     */
    constructor() { 
        
        ServicePhoneNumberSearchOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServicePhoneNumberSearchOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServicePhoneNumberSearchOutput} obj Optional instance to populate.
     * @return {module:model/ServicePhoneNumberSearchOutput} The populated <code>ServicePhoneNumberSearchOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServicePhoneNumberSearchOutput();

            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServicePhoneNumberSearchOutput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServicePhoneNumberSearchOutput</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['phoneNumber'] && !(typeof data['phoneNumber'] === 'string' || data['phoneNumber'] instanceof String)) {
            throw new Error("Expected the field `phoneNumber` to be a primitive type in the JSON string but got " + data['phoneNumber']);
        }

        return true;
    }


}



/**
 * @member {String} phoneNumber
 */
ServicePhoneNumberSearchOutput.prototype['phoneNumber'] = undefined;






export default ServicePhoneNumberSearchOutput;

