/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceQueueRecipientOutputRecipient from './ServiceQueueRecipientOutputRecipient';

/**
 * The ServiceQueueRecipientOutput model module.
 * @module model/ServiceQueueRecipientOutput
 * @version 1.1
 */
class ServiceQueueRecipientOutput {
    /**
     * Constructs a new <code>ServiceQueueRecipientOutput</code>.
     * @alias module:model/ServiceQueueRecipientOutput
     */
    constructor() { 
        
        ServiceQueueRecipientOutput.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceQueueRecipientOutput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceQueueRecipientOutput} obj Optional instance to populate.
     * @return {module:model/ServiceQueueRecipientOutput} The populated <code>ServiceQueueRecipientOutput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceQueueRecipientOutput();

            if (data.hasOwnProperty('display_name')) {
                obj['display_name'] = ApiClient.convertToType(data['display_name'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = ServiceQueueRecipientOutputRecipient.constructFromObject(data['recipient']);
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], {'String': 'String'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceQueueRecipientOutput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceQueueRecipientOutput</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['display_name'] && !(typeof data['display_name'] === 'string' || data['display_name'] instanceof String)) {
            throw new Error("Expected the field `display_name` to be a primitive type in the JSON string but got " + data['display_name']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // validate the optional field `recipient`
        if (data['recipient']) { // data not null
          ServiceQueueRecipientOutputRecipient.validateJSON(data['recipient']);
        }

        return true;
    }


}



/**
 * @member {String} display_name
 */
ServiceQueueRecipientOutput.prototype['display_name'] = undefined;

/**
 * @member {String} id
 */
ServiceQueueRecipientOutput.prototype['id'] = undefined;

/**
 * @member {String} name
 */
ServiceQueueRecipientOutput.prototype['name'] = undefined;

/**
 * @member {module:model/ServiceQueueRecipientOutputRecipient} recipient
 */
ServiceQueueRecipientOutput.prototype['recipient'] = undefined;

/**
 * @member {Object.<String, String>} roles
 */
ServiceQueueRecipientOutput.prototype['roles'] = undefined;






export default ServiceQueueRecipientOutput;

