/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import ServiceCallQueueStatusStats;

/**
 * ServiceCallQueueStatusOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceCallQueueStatusOutput {
  @.annotation.Nullable
  private Number activeRecipientCount;

  @.annotation.Nullable
  private Number availableRecipientCount;

  @.annotation.Nullable
  private String node;

  @.annotation.Nullable
  private ServiceCallQueueStatusStats stats;

  public ServiceCallQueueStatusOutput() {
  }

  public ServiceCallQueueStatusOutput activeRecipientCount(@.annotation.Nullable Number activeRecipientCount) {
    
    this.activeRecipientCount = activeRecipientCount;
    return this;
  }

  /**
   * Get activeRecipientCount
   * @return activeRecipientCount
   */
  @.annotation.Nullable

  public Number getActiveRecipientCount() {
    return activeRecipientCount;
  }


  public void setActiveRecipientCount(@.annotation.Nullable Number activeRecipientCount) {
    this.activeRecipientCount = activeRecipientCount;
  }

  public ServiceCallQueueStatusOutput availableRecipientCount(@.annotation.Nullable Number availableRecipientCount) {
    
    this.availableRecipientCount = availableRecipientCount;
    return this;
  }

  /**
   * Get availableRecipientCount
   * @return availableRecipientCount
   */
  @.annotation.Nullable

  public Number getAvailableRecipientCount() {
    return availableRecipientCount;
  }


  public void setAvailableRecipientCount(@.annotation.Nullable Number availableRecipientCount) {
    this.availableRecipientCount = availableRecipientCount;
  }

  public ServiceCallQueueStatusOutput node(@.annotation.Nullable String node) {
    
    this.node = node;
    return this;
  }

  /**
   * Get node
   * @return node
   */
  @.annotation.Nullable

  public String getNode() {
    return node;
  }


  public void setNode(@.annotation.Nullable String node) {
    this.node = node;
  }

  public ServiceCallQueueStatusOutput stats(@.annotation.Nullable ServiceCallQueueStatusStats stats) {
    
    this.stats = stats;
    return this;
  }

  /**
   * Get stats
   * @return stats
   */
  @.annotation.Nullable

  public ServiceCallQueueStatusStats getStats() {
    return stats;
  }


  public void setStats(@.annotation.Nullable ServiceCallQueueStatusStats stats) {
    this.stats = stats;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceCallQueueStatusOutput serviceCallQueueStatusOutput = (ServiceCallQueueStatusOutput) o;
    return Objects.equals(this.activeRecipientCount, serviceCallQueueStatusOutput.activeRecipientCount) &&
        Objects.equals(this.availableRecipientCount, serviceCallQueueStatusOutput.availableRecipientCount) &&
        Objects.equals(this.node, serviceCallQueueStatusOutput.node) &&
        Objects.equals(this.stats, serviceCallQueueStatusOutput.stats);
  }

  @Override
  public int hashCode() {
    return Objects.hash(activeRecipientCount, availableRecipientCount, node, stats);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceCallQueueStatusOutput {\n");
    sb.append("    activeRecipientCount: ").append(toIndentedString(activeRecipientCount)).append("\n");
    sb.append("    availableRecipientCount: ").append(toIndentedString(availableRecipientCount)).append("\n");
    sb.append("    node: ").append(toIndentedString(node)).append("\n");
    sb.append("    stats: ").append(toIndentedString(stats)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

