/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceDeviceOutputFullMediaAudio model module.
 * @module model/ServiceDeviceOutputFullMediaAudio
 * @version 1.1
 */
class ServiceDeviceOutputFullMediaAudio {
    /**
     * Constructs a new <code>ServiceDeviceOutputFullMediaAudio</code>.
     * @alias module:model/ServiceDeviceOutputFullMediaAudio
     */
    constructor() { 
        
        ServiceDeviceOutputFullMediaAudio.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceDeviceOutputFullMediaAudio</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceDeviceOutputFullMediaAudio} obj Optional instance to populate.
     * @return {module:model/ServiceDeviceOutputFullMediaAudio} The populated <code>ServiceDeviceOutputFullMediaAudio</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceDeviceOutputFullMediaAudio();

            if (data.hasOwnProperty('codecs')) {
                obj['codecs'] = ApiClient.convertToType(data['codecs'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceDeviceOutputFullMediaAudio</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceDeviceOutputFullMediaAudio</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['codecs'])) {
            throw new Error("Expected the field `codecs` to be an array in the JSON data but got " + data['codecs']);
        }

        return true;
    }


}



/**
 * @member {Array.<String>} codecs
 */
ServiceDeviceOutputFullMediaAudio.prototype['codecs'] = undefined;






export default ServiceDeviceOutputFullMediaAudio;

