/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceMenuOutputFullMedia from './ServiceMenuOutputFullMedia';

/**
 * The ServiceMenuOutputFull model module.
 * @module model/ServiceMenuOutputFull
 * @version 1.1
 */
class ServiceMenuOutputFull {
    /**
     * Constructs a new <code>ServiceMenuOutputFull</code>.
     * @alias module:model/ServiceMenuOutputFull
     */
    constructor() { 
        
        ServiceMenuOutputFull.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceMenuOutputFull</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceMenuOutputFull} obj Optional instance to populate.
     * @return {module:model/ServiceMenuOutputFull} The populated <code>ServiceMenuOutputFull</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceMenuOutputFull();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ServiceMenuOutputFullMedia.constructFromObject(data['media']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('timeout')) {
                obj['timeout'] = ApiClient.convertToType(data['timeout'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceMenuOutputFull</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceMenuOutputFull</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `media`
        if (data['media']) { // data not null
          ServiceMenuOutputFullMedia.validateJSON(data['media']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}



/**
 * @member {String} id
 */
ServiceMenuOutputFull.prototype['id'] = undefined;

/**
 * @member {module:model/ServiceMenuOutputFullMedia} media
 */
ServiceMenuOutputFull.prototype['media'] = undefined;

/**
 * @member {String} name
 */
ServiceMenuOutputFull.prototype['name'] = undefined;

/**
 * @member {Number} timeout
 */
ServiceMenuOutputFull.prototype['timeout'] = undefined;






export default ServiceMenuOutputFull;

