/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceCallQueueStatusStats model module.
 * @module model/ServiceCallQueueStatusStats
 * @version 1.1
 */
class ServiceCallQueueStatusStats {
    /**
     * Constructs a new <code>ServiceCallQueueStatusStats</code>.
     * @alias module:model/ServiceCallQueueStatusStats
     */
    constructor() { 
        
        ServiceCallQueueStatusStats.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceCallQueueStatusStats</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceCallQueueStatusStats} obj Optional instance to populate.
     * @return {module:model/ServiceCallQueueStatusStats} The populated <code>ServiceCallQueueStatusStats</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceCallQueueStatusStats();

            if (data.hasOwnProperty('abandoned_sessions')) {
                obj['abandoned_sessions'] = ApiClient.convertToType(data['abandoned_sessions'], 'Number');
            }
            if (data.hasOwnProperty('active_session_count')) {
                obj['active_session_count'] = ApiClient.convertToType(data['active_session_count'], 'Number');
            }
            if (data.hasOwnProperty('average_wait')) {
                obj['average_wait'] = ApiClient.convertToType(data['average_wait'], 'Number');
            }
            if (data.hasOwnProperty('estimated_wait')) {
                obj['estimated_wait'] = ApiClient.convertToType(data['estimated_wait'], 'Number');
            }
            if (data.hasOwnProperty('longest_wait')) {
                obj['longest_wait'] = ApiClient.convertToType(data['longest_wait'], 'Number');
            }
            if (data.hasOwnProperty('missed_sessions')) {
                obj['missed_sessions'] = ApiClient.convertToType(data['missed_sessions'], 'Number');
            }
            if (data.hasOwnProperty('recipient_count')) {
                obj['recipient_count'] = ApiClient.convertToType(data['recipient_count'], 'Number');
            }
            if (data.hasOwnProperty('total_sessions')) {
                obj['total_sessions'] = ApiClient.convertToType(data['total_sessions'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceCallQueueStatusStats</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceCallQueueStatusStats</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} abandoned_sessions
 */
ServiceCallQueueStatusStats.prototype['abandoned_sessions'] = undefined;

/**
 * @member {Number} active_session_count
 */
ServiceCallQueueStatusStats.prototype['active_session_count'] = undefined;

/**
 * @member {Number} average_wait
 */
ServiceCallQueueStatusStats.prototype['average_wait'] = undefined;

/**
 * @member {Number} estimated_wait
 */
ServiceCallQueueStatusStats.prototype['estimated_wait'] = undefined;

/**
 * @member {Number} longest_wait
 */
ServiceCallQueueStatusStats.prototype['longest_wait'] = undefined;

/**
 * @member {Number} missed_sessions
 */
ServiceCallQueueStatusStats.prototype['missed_sessions'] = undefined;

/**
 * @member {Number} recipient_count
 */
ServiceCallQueueStatusStats.prototype['recipient_count'] = undefined;

/**
 * @member {Number} total_sessions
 */
ServiceCallQueueStatusStats.prototype['total_sessions'] = undefined;






export default ServiceCallQueueStatusStats;

