/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceCallRecordingOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceCallRecordingOutput {
  @.annotation.Nullable
  private String callId;

  @.annotation.Nullable
  private String calleeIdName;

  @.annotation.Nullable
  private String calleeIdNumber;

  @.annotation.Nullable
  private String callerIdName;

  @.annotation.Nullable
  private String callerIdNumber;

  @.annotation.Nullable
  private String cdrId;

  @.annotation.Nullable
  private String contentType;

  @.annotation.Nullable
  private {String: Object} customChannelVars;

  @.annotation.Nullable
  private String description;

  @.annotation.Nullable
  private String direction;

  @.annotation.Nullable
  private Number duration;

  @.annotation.Nullable
  private Number durationMs;

  @.annotation.Nullable
  private String endpointId;

  @.annotation.Nullable
  private String from;

  @.annotation.Nullable
  private String id;

  @.annotation.Nullable
  private String interactionId;

  @.annotation.Nullable
  private String mediaSource;

  @.annotation.Nullable
  private String mediaType;

  @.annotation.Nullable
  private String name;

  @.annotation.Nullable
  private String origin;

  @.annotation.Nullable
  private String ownerId;

  @.annotation.Nullable
  private String request;

  @.annotation.Nullable
  private String sourceType;

  @.annotation.Nullable
  private Number start;

  @.annotation.Nullable
  private String to;

  @.annotation.Nullable
  private String url;

  public ServiceCallRecordingOutput() {
  }

  public ServiceCallRecordingOutput callId(@.annotation.Nullable String callId) {
    
    this.callId = callId;
    return this;
  }

  /**
   * Get callId
   * @return callId
   */
  @.annotation.Nullable

  public String getCallId() {
    return callId;
  }


  public void setCallId(@.annotation.Nullable String callId) {
    this.callId = callId;
  }

  public ServiceCallRecordingOutput calleeIdName(@.annotation.Nullable String calleeIdName) {
    
    this.calleeIdName = calleeIdName;
    return this;
  }

  /**
   * Get calleeIdName
   * @return calleeIdName
   */
  @.annotation.Nullable

  public String getCalleeIdName() {
    return calleeIdName;
  }


  public void setCalleeIdName(@.annotation.Nullable String calleeIdName) {
    this.calleeIdName = calleeIdName;
  }

  public ServiceCallRecordingOutput calleeIdNumber(@.annotation.Nullable String calleeIdNumber) {
    
    this.calleeIdNumber = calleeIdNumber;
    return this;
  }

  /**
   * Get calleeIdNumber
   * @return calleeIdNumber
   */
  @.annotation.Nullable

  public String getCalleeIdNumber() {
    return calleeIdNumber;
  }


  public void setCalleeIdNumber(@.annotation.Nullable String calleeIdNumber) {
    this.calleeIdNumber = calleeIdNumber;
  }

  public ServiceCallRecordingOutput callerIdName(@.annotation.Nullable String callerIdName) {
    
    this.callerIdName = callerIdName;
    return this;
  }

  /**
   * Get callerIdName
   * @return callerIdName
   */
  @.annotation.Nullable

  public String getCallerIdName() {
    return callerIdName;
  }


  public void setCallerIdName(@.annotation.Nullable String callerIdName) {
    this.callerIdName = callerIdName;
  }

  public ServiceCallRecordingOutput callerIdNumber(@.annotation.Nullable String callerIdNumber) {
    
    this.callerIdNumber = callerIdNumber;
    return this;
  }

  /**
   * Get callerIdNumber
   * @return callerIdNumber
   */
  @.annotation.Nullable

  public String getCallerIdNumber() {
    return callerIdNumber;
  }


  public void setCallerIdNumber(@.annotation.Nullable String callerIdNumber) {
    this.callerIdNumber = callerIdNumber;
  }

  public ServiceCallRecordingOutput cdrId(@.annotation.Nullable String cdrId) {
    
    this.cdrId = cdrId;
    return this;
  }

  /**
   * Get cdrId
   * @return cdrId
   */
  @.annotation.Nullable

  public String getCdrId() {
    return cdrId;
  }


  public void setCdrId(@.annotation.Nullable String cdrId) {
    this.cdrId = cdrId;
  }

  public ServiceCallRecordingOutput contentType(@.annotation.Nullable String contentType) {
    
    this.contentType = contentType;
    return this;
  }

  /**
   * Get contentType
   * @return contentType
   */
  @.annotation.Nullable

  public String getContentType() {
    return contentType;
  }


  public void setContentType(@.annotation.Nullable String contentType) {
    this.contentType = contentType;
  }

  public ServiceCallRecordingOutput customChannelVars(@.annotation.Nullable {String: Object} customChannelVars) {
    
    this.customChannelVars = customChannelVars;
    return this;
  }

  public ServiceCallRecordingOutput putCustomChannelVarsItem(String key, Object customChannelVarsItem) {
    if (this.customChannelVars == null) {
      this.customChannelVars = new HashMap<>();
    }
    this.customChannelVars.put(key, customChannelVarsItem);
    return this;
  }

  /**
   * Get customChannelVars
   * @return customChannelVars
   */
  @.annotation.Nullable

  public {String: Object} getCustomChannelVars() {
    return customChannelVars;
  }


  public void setCustomChannelVars(@.annotation.Nullable {String: Object} customChannelVars) {
    this.customChannelVars = customChannelVars;
  }

  public ServiceCallRecordingOutput description(@.annotation.Nullable String description) {
    
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @.annotation.Nullable

  public String getDescription() {
    return description;
  }


  public void setDescription(@.annotation.Nullable String description) {
    this.description = description;
  }

  public ServiceCallRecordingOutput direction(@.annotation.Nullable String direction) {
    
    this.direction = direction;
    return this;
  }

  /**
   * Get direction
   * @return direction
   */
  @.annotation.Nullable

  public String getDirection() {
    return direction;
  }


  public void setDirection(@.annotation.Nullable String direction) {
    this.direction = direction;
  }

  public ServiceCallRecordingOutput duration(@.annotation.Nullable Number duration) {
    
    this.duration = duration;
    return this;
  }

  /**
   * Get duration
   * @return duration
   */
  @.annotation.Nullable

  public Number getDuration() {
    return duration;
  }


  public void setDuration(@.annotation.Nullable Number duration) {
    this.duration = duration;
  }

  public ServiceCallRecordingOutput durationMs(@.annotation.Nullable Number durationMs) {
    
    this.durationMs = durationMs;
    return this;
  }

  /**
   * Get durationMs
   * @return durationMs
   */
  @.annotation.Nullable

  public Number getDurationMs() {
    return durationMs;
  }


  public void setDurationMs(@.annotation.Nullable Number durationMs) {
    this.durationMs = durationMs;
  }

  public ServiceCallRecordingOutput endpointId(@.annotation.Nullable String endpointId) {
    
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Get endpointId
   * @return endpointId
   */
  @.annotation.Nullable

  public String getEndpointId() {
    return endpointId;
  }


  public void setEndpointId(@.annotation.Nullable String endpointId) {
    this.endpointId = endpointId;
  }

  public ServiceCallRecordingOutput from(@.annotation.Nullable String from) {
    
    this.from = from;
    return this;
  }

  /**
   * Get from
   * @return from
   */
  @.annotation.Nullable

  public String getFrom() {
    return from;
  }


  public void setFrom(@.annotation.Nullable String from) {
    this.from = from;
  }

  public ServiceCallRecordingOutput id(@.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @.annotation.Nullable

  public String getId() {
    return id;
  }


  public void setId(@.annotation.Nullable String id) {
    this.id = id;
  }

  public ServiceCallRecordingOutput interactionId(@.annotation.Nullable String interactionId) {
    
    this.interactionId = interactionId;
    return this;
  }

  /**
   * Get interactionId
   * @return interactionId
   */
  @.annotation.Nullable

  public String getInteractionId() {
    return interactionId;
  }


  public void setInteractionId(@.annotation.Nullable String interactionId) {
    this.interactionId = interactionId;
  }

  public ServiceCallRecordingOutput mediaSource(@.annotation.Nullable String mediaSource) {
    
    this.mediaSource = mediaSource;
    return this;
  }

  /**
   * Get mediaSource
   * @return mediaSource
   */
  @.annotation.Nullable

  public String getMediaSource() {
    return mediaSource;
  }


  public void setMediaSource(@.annotation.Nullable String mediaSource) {
    this.mediaSource = mediaSource;
  }

  public ServiceCallRecordingOutput mediaType(@.annotation.Nullable String mediaType) {
    
    this.mediaType = mediaType;
    return this;
  }

  /**
   * Get mediaType
   * @return mediaType
   */
  @.annotation.Nullable

  public String getMediaType() {
    return mediaType;
  }


  public void setMediaType(@.annotation.Nullable String mediaType) {
    this.mediaType = mediaType;
  }

  public ServiceCallRecordingOutput name(@.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@.annotation.Nullable String name) {
    this.name = name;
  }

  public ServiceCallRecordingOutput origin(@.annotation.Nullable String origin) {
    
    this.origin = origin;
    return this;
  }

  /**
   * Get origin
   * @return origin
   */
  @.annotation.Nullable

  public String getOrigin() {
    return origin;
  }


  public void setOrigin(@.annotation.Nullable String origin) {
    this.origin = origin;
  }

  public ServiceCallRecordingOutput ownerId(@.annotation.Nullable String ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   */
  @.annotation.Nullable

  public String getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(@.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
  }

  public ServiceCallRecordingOutput request(@.annotation.Nullable String request) {
    
    this.request = request;
    return this;
  }

  /**
   * Get request
   * @return request
   */
  @.annotation.Nullable

  public String getRequest() {
    return request;
  }


  public void setRequest(@.annotation.Nullable String request) {
    this.request = request;
  }

  public ServiceCallRecordingOutput sourceType(@.annotation.Nullable String sourceType) {
    
    this.sourceType = sourceType;
    return this;
  }

  /**
   * Get sourceType
   * @return sourceType
   */
  @.annotation.Nullable

  public String getSourceType() {
    return sourceType;
  }


  public void setSourceType(@.annotation.Nullable String sourceType) {
    this.sourceType = sourceType;
  }

  public ServiceCallRecordingOutput start(@.annotation.Nullable Number start) {
    
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @.annotation.Nullable

  public Number getStart() {
    return start;
  }


  public void setStart(@.annotation.Nullable Number start) {
    this.start = start;
  }

  public ServiceCallRecordingOutput to(@.annotation.Nullable String to) {
    
    this.to = to;
    return this;
  }

  /**
   * Get to
   * @return to
   */
  @.annotation.Nullable

  public String getTo() {
    return to;
  }


  public void setTo(@.annotation.Nullable String to) {
    this.to = to;
  }

  public ServiceCallRecordingOutput url(@.annotation.Nullable String url) {
    
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @.annotation.Nullable

  public String getUrl() {
    return url;
  }


  public void setUrl(@.annotation.Nullable String url) {
    this.url = url;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceCallRecordingOutput serviceCallRecordingOutput = (ServiceCallRecordingOutput) o;
    return Objects.equals(this.callId, serviceCallRecordingOutput.callId) &&
        Objects.equals(this.calleeIdName, serviceCallRecordingOutput.calleeIdName) &&
        Objects.equals(this.calleeIdNumber, serviceCallRecordingOutput.calleeIdNumber) &&
        Objects.equals(this.callerIdName, serviceCallRecordingOutput.callerIdName) &&
        Objects.equals(this.callerIdNumber, serviceCallRecordingOutput.callerIdNumber) &&
        Objects.equals(this.cdrId, serviceCallRecordingOutput.cdrId) &&
        Objects.equals(this.contentType, serviceCallRecordingOutput.contentType) &&
        Objects.equals(this.customChannelVars, serviceCallRecordingOutput.customChannelVars) &&
        Objects.equals(this.description, serviceCallRecordingOutput.description) &&
        Objects.equals(this.direction, serviceCallRecordingOutput.direction) &&
        Objects.equals(this.duration, serviceCallRecordingOutput.duration) &&
        Objects.equals(this.durationMs, serviceCallRecordingOutput.durationMs) &&
        Objects.equals(this.endpointId, serviceCallRecordingOutput.endpointId) &&
        Objects.equals(this.from, serviceCallRecordingOutput.from) &&
        Objects.equals(this.id, serviceCallRecordingOutput.id) &&
        Objects.equals(this.interactionId, serviceCallRecordingOutput.interactionId) &&
        Objects.equals(this.mediaSource, serviceCallRecordingOutput.mediaSource) &&
        Objects.equals(this.mediaType, serviceCallRecordingOutput.mediaType) &&
        Objects.equals(this.name, serviceCallRecordingOutput.name) &&
        Objects.equals(this.origin, serviceCallRecordingOutput.origin) &&
        Objects.equals(this.ownerId, serviceCallRecordingOutput.ownerId) &&
        Objects.equals(this.request, serviceCallRecordingOutput.request) &&
        Objects.equals(this.sourceType, serviceCallRecordingOutput.sourceType) &&
        Objects.equals(this.start, serviceCallRecordingOutput.start) &&
        Objects.equals(this.to, serviceCallRecordingOutput.to) &&
        Objects.equals(this.url, serviceCallRecordingOutput.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callId, calleeIdName, calleeIdNumber, callerIdName, callerIdNumber, cdrId, contentType, customChannelVars, description, direction, duration, durationMs, endpointId, from, id, interactionId, mediaSource, mediaType, name, origin, ownerId, request, sourceType, start, to, url);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceCallRecordingOutput {\n");
    sb.append("    callId: ").append(toIndentedString(callId)).append("\n");
    sb.append("    calleeIdName: ").append(toIndentedString(calleeIdName)).append("\n");
    sb.append("    calleeIdNumber: ").append(toIndentedString(calleeIdNumber)).append("\n");
    sb.append("    callerIdName: ").append(toIndentedString(callerIdName)).append("\n");
    sb.append("    callerIdNumber: ").append(toIndentedString(callerIdNumber)).append("\n");
    sb.append("    cdrId: ").append(toIndentedString(cdrId)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    customChannelVars: ").append(toIndentedString(customChannelVars)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    direction: ").append(toIndentedString(direction)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    durationMs: ").append(toIndentedString(durationMs)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    interactionId: ").append(toIndentedString(interactionId)).append("\n");
    sb.append("    mediaSource: ").append(toIndentedString(mediaSource)).append("\n");
    sb.append("    mediaType: ").append(toIndentedString(mediaType)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    sourceType: ").append(toIndentedString(sourceType)).append("\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

