/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceVOIPCallQueueRecipientLoginLogoutData
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVOIPCallQueueRecipientLoginLogoutData {
  /**
   * Gets or Sets action
   */
  public enum ActionEnum {
    login(String.valueOf("login")),
    
    logout(String.valueOf("logout"));

    private String value;

    ActionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ActionEnum fromValue(String value) {
      for (ActionEnum b : ActionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @.annotation.Nonnull
  private ActionEnum action;

  public ServiceVOIPCallQueueRecipientLoginLogoutData() {
  }

  public ServiceVOIPCallQueueRecipientLoginLogoutData action(@.annotation.Nonnull ActionEnum action) {
    
    this.action = action;
    return this;
  }

  /**
   * Get action
   * @return action
   */
  @.annotation.Nonnull

  public ActionEnum getAction() {
    return action;
  }


  public void setAction(@.annotation.Nonnull ActionEnum action) {
    this.action = action;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVOIPCallQueueRecipientLoginLogoutData serviceVOIPCallQueueRecipientLoginLogoutData = (ServiceVOIPCallQueueRecipientLoginLogoutData) o;
    return Objects.equals(this.action, serviceVOIPCallQueueRecipientLoginLogoutData.action);
  }

  @Override
  public int hashCode() {
    return Objects.hash(action);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVOIPCallQueueRecipientLoginLogoutData {\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

