/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceCallForward from './ServiceCallForward';
import ServiceCallRecordingSettings from './ServiceCallRecordingSettings';
import ServiceDeviceOutputFullCallerid from './ServiceDeviceOutputFullCallerid';
import ServiceDeviceOutputFullSIP from './ServiceDeviceOutputFullSIP';
import ServiceMusicOnHold from './ServiceMusicOnHold';
import ServiceVOIPSharedDoNotDisturb from './ServiceVOIPSharedDoNotDisturb';

/**
 * The ServiceDeviceOutputFull model module.
 * @module model/ServiceDeviceOutputFull
 * @version 1.1
 */
class ServiceDeviceOutputFull {
    /**
     * Constructs a new <code>ServiceDeviceOutputFull</code>.
     * @alias module:model/ServiceDeviceOutputFull
     */
    constructor() { 
        
        ServiceDeviceOutputFull.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceDeviceOutputFull</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceDeviceOutputFull} obj Optional instance to populate.
     * @return {module:model/ServiceDeviceOutputFull} The populated <code>ServiceDeviceOutputFull</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceDeviceOutputFull();

            if (data.hasOwnProperty('call_forward')) {
                obj['call_forward'] = ServiceCallForward.constructFromObject(data['call_forward']);
            }
            if (data.hasOwnProperty('call_recording')) {
                obj['call_recording'] = ServiceCallRecordingSettings.constructFromObject(data['call_recording']);
            }
            if (data.hasOwnProperty('caller_id')) {
                obj['caller_id'] = ServiceDeviceOutputFullCallerid.constructFromObject(data['caller_id']);
            }
            if (data.hasOwnProperty('device_type')) {
                obj['device_type'] = ApiClient.convertToType(data['device_type'], 'String');
            }
            if (data.hasOwnProperty('do_not_disturb')) {
                obj['do_not_disturb'] = ServiceVOIPSharedDoNotDisturb.constructFromObject(data['do_not_disturb']);
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('mac_address')) {
                obj['mac_address'] = ApiClient.convertToType(data['mac_address'], 'String');
            }
            if (data.hasOwnProperty('music_on_hold')) {
                obj['music_on_hold'] = ApiClient.convertToType(data['music_on_hold'], ServiceMusicOnHold);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('owner_id')) {
                obj['owner_id'] = ApiClient.convertToType(data['owner_id'], 'String');
            }
            if (data.hasOwnProperty('sip')) {
                obj['sip'] = ServiceDeviceOutputFullSIP.constructFromObject(data['sip']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceDeviceOutputFull</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceDeviceOutputFull</code>.
     */
    static validateJSON(data) {
        // validate the optional field `call_forward`
        if (data['call_forward']) { // data not null
          ServiceCallForward.validateJSON(data['call_forward']);
        }
        // validate the optional field `call_recording`
        if (data['call_recording']) { // data not null
          ServiceCallRecordingSettings.validateJSON(data['call_recording']);
        }
        // validate the optional field `caller_id`
        if (data['caller_id']) { // data not null
          ServiceDeviceOutputFullCallerid.validateJSON(data['caller_id']);
        }
        // ensure the json data is a string
        if (data['device_type'] && !(typeof data['device_type'] === 'string' || data['device_type'] instanceof String)) {
            throw new Error("Expected the field `device_type` to be a primitive type in the JSON string but got " + data['device_type']);
        }
        // validate the optional field `do_not_disturb`
        if (data['do_not_disturb']) { // data not null
          ServiceVOIPSharedDoNotDisturb.validateJSON(data['do_not_disturb']);
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['mac_address'] && !(typeof data['mac_address'] === 'string' || data['mac_address'] instanceof String)) {
            throw new Error("Expected the field `mac_address` to be a primitive type in the JSON string but got " + data['mac_address']);
        }
        // validate the optional field `music_on_hold`
        if (data['music_on_hold']) { // data not null
          ServiceMusicOnHold.validateJSON(data['music_on_hold']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['owner_id'] && !(typeof data['owner_id'] === 'string' || data['owner_id'] instanceof String)) {
            throw new Error("Expected the field `owner_id` to be a primitive type in the JSON string but got " + data['owner_id']);
        }
        // validate the optional field `sip`
        if (data['sip']) { // data not null
          ServiceDeviceOutputFullSIP.validateJSON(data['sip']);
        }

        return true;
    }


}



/**
 * @member {module:model/ServiceCallForward} call_forward
 */
ServiceDeviceOutputFull.prototype['call_forward'] = undefined;

/**
 * @member {module:model/ServiceCallRecordingSettings} call_recording
 */
ServiceDeviceOutputFull.prototype['call_recording'] = undefined;

/**
 * @member {module:model/ServiceDeviceOutputFullCallerid} caller_id
 */
ServiceDeviceOutputFull.prototype['caller_id'] = undefined;

/**
 * @member {String} device_type
 */
ServiceDeviceOutputFull.prototype['device_type'] = undefined;

/**
 * @member {module:model/ServiceVOIPSharedDoNotDisturb} do_not_disturb
 */
ServiceDeviceOutputFull.prototype['do_not_disturb'] = undefined;

/**
 * @member {Boolean} enabled
 */
ServiceDeviceOutputFull.prototype['enabled'] = undefined;

/**
 * @member {String} id
 */
ServiceDeviceOutputFull.prototype['id'] = undefined;

/**
 * @member {String} mac_address
 */
ServiceDeviceOutputFull.prototype['mac_address'] = undefined;

/**
 * Provision  *DeviceOutputFullProvision `json:\"provision\"`
 * @member {module:model/ServiceMusicOnHold} music_on_hold
 */
ServiceDeviceOutputFull.prototype['music_on_hold'] = undefined;

/**
 * @member {String} name
 */
ServiceDeviceOutputFull.prototype['name'] = undefined;

/**
 * @member {String} owner_id
 */
ServiceDeviceOutputFull.prototype['owner_id'] = undefined;

/**
 * @member {module:model/ServiceDeviceOutputFullSIP} sip
 */
ServiceDeviceOutputFull.prototype['sip'] = undefined;






export default ServiceDeviceOutputFull;

