/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceMusicOnHold
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceMusicOnHold {
  @.annotation.Nullable
  private String mediaId;

  public ServiceMusicOnHold() {
  }

  public ServiceMusicOnHold mediaId(@.annotation.Nullable String mediaId) {
    
    this.mediaId = mediaId;
    return this;
  }

  /**
   * Get mediaId
   * @return mediaId
   */
  @.annotation.Nullable

  public String getMediaId() {
    return mediaId;
  }


  public void setMediaId(@.annotation.Nullable String mediaId) {
    this.mediaId = mediaId;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceMusicOnHold serviceMusicOnHold = (ServiceMusicOnHold) o;
    return Objects.equals(this.mediaId, serviceMusicOnHold.mediaId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mediaId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceMusicOnHold {\n");
    sb.append("    mediaId: ").append(toIndentedString(mediaId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

