/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ServiceE911LocationURILegacyData model module.
 * @module model/ServiceE911LocationURILegacyData
 * @version 1.1
 */
class ServiceE911LocationURILegacyData {
    /**
     * Constructs a new <code>ServiceE911LocationURILegacyData</code>.
     * @alias module:model/ServiceE911LocationURILegacyData
     */
    constructor() { 
        
        ServiceE911LocationURILegacyData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ServiceE911LocationURILegacyData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceE911LocationURILegacyData} obj Optional instance to populate.
     * @return {module:model/ServiceE911LocationURILegacyData} The populated <code>ServiceE911LocationURILegacyData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceE911LocationURILegacyData();

            if (data.hasOwnProperty('houseNumber')) {
                obj['houseNumber'] = ApiClient.convertToType(data['houseNumber'], 'String');
            }
            if (data.hasOwnProperty('predirectional')) {
                obj['predirectional'] = ApiClient.convertToType(data['predirectional'], 'String');
            }
            if (data.hasOwnProperty('streetName')) {
                obj['streetName'] = ApiClient.convertToType(data['streetName'], 'String');
            }
            if (data.hasOwnProperty('suite')) {
                obj['suite'] = ApiClient.convertToType(data['suite'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceE911LocationURILegacyData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceE911LocationURILegacyData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['houseNumber'] && !(typeof data['houseNumber'] === 'string' || data['houseNumber'] instanceof String)) {
            throw new Error("Expected the field `houseNumber` to be a primitive type in the JSON string but got " + data['houseNumber']);
        }
        // ensure the json data is a string
        if (data['predirectional'] && !(typeof data['predirectional'] === 'string' || data['predirectional'] instanceof String)) {
            throw new Error("Expected the field `predirectional` to be a primitive type in the JSON string but got " + data['predirectional']);
        }
        // ensure the json data is a string
        if (data['streetName'] && !(typeof data['streetName'] === 'string' || data['streetName'] instanceof String)) {
            throw new Error("Expected the field `streetName` to be a primitive type in the JSON string but got " + data['streetName']);
        }
        // ensure the json data is a string
        if (data['suite'] && !(typeof data['suite'] === 'string' || data['suite'] instanceof String)) {
            throw new Error("Expected the field `suite` to be a primitive type in the JSON string but got " + data['suite']);
        }

        return true;
    }


}



/**
 * @member {String} houseNumber
 */
ServiceE911LocationURILegacyData.prototype['houseNumber'] = undefined;

/**
 * @member {String} predirectional
 */
ServiceE911LocationURILegacyData.prototype['predirectional'] = undefined;

/**
 * @member {String} streetName
 */
ServiceE911LocationURILegacyData.prototype['streetName'] = undefined;

/**
 * @member {String} suite
 */
ServiceE911LocationURILegacyData.prototype['suite'] = undefined;






export default ServiceE911LocationURILegacyData;

