/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import ServiceVoicemailMedia;

/**
 * ServiceVoicemailOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceVoicemailOutput {
  @.annotation.Nullable
  private String id;

  @.annotation.Nullable
  private String mailbox;

  @.annotation.Nullable
  private ServiceVoicemailMedia media;

  @.annotation.Nullable
  private String mediaExtension;

  @.annotation.Nullable
  private Number messages;

  @.annotation.Nullable
  private String name;

  @.annotation.Nullable
  private String ownerId;

  @.annotation.Nullable
  private String pin;

  @.annotation.Nullable
  private Boolean requirePin;

  @.annotation.Nullable
  private String timezone;

  public ServiceVoicemailOutput() {
  }

  public ServiceVoicemailOutput id(@.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @.annotation.Nullable

  public String getId() {
    return id;
  }


  public void setId(@.annotation.Nullable String id) {
    this.id = id;
  }

  public ServiceVoicemailOutput mailbox(@.annotation.Nullable String mailbox) {
    
    this.mailbox = mailbox;
    return this;
  }

  /**
   * Get mailbox
   * @return mailbox
   */
  @.annotation.Nullable

  public String getMailbox() {
    return mailbox;
  }


  public void setMailbox(@.annotation.Nullable String mailbox) {
    this.mailbox = mailbox;
  }

  public ServiceVoicemailOutput media(@.annotation.Nullable ServiceVoicemailMedia media) {
    
    this.media = media;
    return this;
  }

  /**
   * Get media
   * @return media
   */
  @.annotation.Nullable

  public ServiceVoicemailMedia getMedia() {
    return media;
  }


  public void setMedia(@.annotation.Nullable ServiceVoicemailMedia media) {
    this.media = media;
  }

  public ServiceVoicemailOutput mediaExtension(@.annotation.Nullable String mediaExtension) {
    
    this.mediaExtension = mediaExtension;
    return this;
  }

  /**
   * Get mediaExtension
   * @return mediaExtension
   */
  @.annotation.Nullable

  public String getMediaExtension() {
    return mediaExtension;
  }


  public void setMediaExtension(@.annotation.Nullable String mediaExtension) {
    this.mediaExtension = mediaExtension;
  }

  public ServiceVoicemailOutput messages(@.annotation.Nullable Number messages) {
    
    this.messages = messages;
    return this;
  }

  /**
   * Get messages
   * @return messages
   */
  @.annotation.Nullable

  public Number getMessages() {
    return messages;
  }


  public void setMessages(@.annotation.Nullable Number messages) {
    this.messages = messages;
  }

  public ServiceVoicemailOutput name(@.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@.annotation.Nullable String name) {
    this.name = name;
  }

  public ServiceVoicemailOutput ownerId(@.annotation.Nullable String ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   */
  @.annotation.Nullable

  public String getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(@.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
  }

  public ServiceVoicemailOutput pin(@.annotation.Nullable String pin) {
    
    this.pin = pin;
    return this;
  }

  /**
   * Get pin
   * @return pin
   */
  @.annotation.Nullable

  public String getPin() {
    return pin;
  }


  public void setPin(@.annotation.Nullable String pin) {
    this.pin = pin;
  }

  public ServiceVoicemailOutput requirePin(@.annotation.Nullable Boolean requirePin) {
    
    this.requirePin = requirePin;
    return this;
  }

  /**
   * Get requirePin
   * @return requirePin
   */
  @.annotation.Nullable

  public Boolean getRequirePin() {
    return requirePin;
  }


  public void setRequirePin(@.annotation.Nullable Boolean requirePin) {
    this.requirePin = requirePin;
  }

  public ServiceVoicemailOutput timezone(@.annotation.Nullable String timezone) {
    
    this.timezone = timezone;
    return this;
  }

  /**
   * Get timezone
   * @return timezone
   */
  @.annotation.Nullable

  public String getTimezone() {
    return timezone;
  }


  public void setTimezone(@.annotation.Nullable String timezone) {
    this.timezone = timezone;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceVoicemailOutput serviceVoicemailOutput = (ServiceVoicemailOutput) o;
    return Objects.equals(this.id, serviceVoicemailOutput.id) &&
        Objects.equals(this.mailbox, serviceVoicemailOutput.mailbox) &&
        Objects.equals(this.media, serviceVoicemailOutput.media) &&
        Objects.equals(this.mediaExtension, serviceVoicemailOutput.mediaExtension) &&
        Objects.equals(this.messages, serviceVoicemailOutput.messages) &&
        Objects.equals(this.name, serviceVoicemailOutput.name) &&
        Objects.equals(this.ownerId, serviceVoicemailOutput.ownerId) &&
        Objects.equals(this.pin, serviceVoicemailOutput.pin) &&
        Objects.equals(this.requirePin, serviceVoicemailOutput.requirePin) &&
        Objects.equals(this.timezone, serviceVoicemailOutput.timezone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, mailbox, media, mediaExtension, messages, name, ownerId, pin, requirePin, timezone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceVoicemailOutput {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mailbox: ").append(toIndentedString(mailbox)).append("\n");
    sb.append("    media: ").append(toIndentedString(media)).append("\n");
    sb.append("    mediaExtension: ").append(toIndentedString(mediaExtension)).append("\n");
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    pin: ").append(toIndentedString(pin)).append("\n");
    sb.append("    requirePin: ").append(toIndentedString(requirePin)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

