/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import ServiceE911ActiveLocationStatus;

/**
 * ServiceE911ActiveLocationOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceE911ActiveLocationOutput {
  @.annotation.Nullable
  private ServiceE911ActiveLocationStatus locationStatus;

  public ServiceE911ActiveLocationOutput() {
  }

  public ServiceE911ActiveLocationOutput locationStatus(@.annotation.Nullable ServiceE911ActiveLocationStatus locationStatus) {
    
    this.locationStatus = locationStatus;
    return this;
  }

  /**
   * Get locationStatus
   * @return locationStatus
   */
  @.annotation.Nullable

  public ServiceE911ActiveLocationStatus getLocationStatus() {
    return locationStatus;
  }


  public void setLocationStatus(@.annotation.Nullable ServiceE911ActiveLocationStatus locationStatus) {
    this.locationStatus = locationStatus;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceE911ActiveLocationOutput serviceE911ActiveLocationOutput = (ServiceE911ActiveLocationOutput) o;
    return Objects.equals(this.locationStatus, serviceE911ActiveLocationOutput.locationStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(locationStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceE911ActiveLocationOutput {\n");
    sb.append("    locationStatus: ").append(toIndentedString(locationStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

