/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import ServiceCallflowAddEditFlowData;
import ServiceFeatureCode;

/**
 * ServiceCallflowAddEditData
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceCallflowAddEditData {
  @.annotation.Nullable
  private ServiceFeatureCode featurecode;

  @.annotation.Nullable
  private ServiceCallflowAddEditFlowData flow;

  @.annotation.Nullable
  private String name;

  @.annotation.Nonnull
  private [String] numbers;

  @.annotation.Nonnull
  private [String] patterns;

  public ServiceCallflowAddEditData() {
  }

  public ServiceCallflowAddEditData featurecode(@.annotation.Nullable ServiceFeatureCode featurecode) {
    
    this.featurecode = featurecode;
    return this;
  }

  /**
   * Get featurecode
   * @return featurecode
   */
  @.annotation.Nullable

  public ServiceFeatureCode getFeaturecode() {
    return featurecode;
  }


  public void setFeaturecode(@.annotation.Nullable ServiceFeatureCode featurecode) {
    this.featurecode = featurecode;
  }

  public ServiceCallflowAddEditData flow(@.annotation.Nullable ServiceCallflowAddEditFlowData flow) {
    
    this.flow = flow;
    return this;
  }

  /**
   * Get flow
   * @return flow
   */
  @.annotation.Nullable

  public ServiceCallflowAddEditFlowData getFlow() {
    return flow;
  }


  public void setFlow(@.annotation.Nullable ServiceCallflowAddEditFlowData flow) {
    this.flow = flow;
  }

  public ServiceCallflowAddEditData name(@.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@.annotation.Nullable String name) {
    this.name = name;
  }

  public ServiceCallflowAddEditData numbers(@.annotation.Nonnull [String] numbers) {
    
    this.numbers = numbers;
    return this;
  }

  public ServiceCallflowAddEditData addNumbersItem(String numbersItem) {
    if (this.numbers == null) {
      this.numbers = new ArrayList<>();
    }
    this.numbers.add(numbersItem);
    return this;
  }

  /**
   * Get numbers
   * @return numbers
   */
  @.annotation.Nonnull

  public [String] getNumbers() {
    return numbers;
  }


  public void setNumbers(@.annotation.Nonnull [String] numbers) {
    this.numbers = numbers;
  }

  public ServiceCallflowAddEditData patterns(@.annotation.Nonnull [String] patterns) {
    
    this.patterns = patterns;
    return this;
  }

  public ServiceCallflowAddEditData addPatternsItem(String patternsItem) {
    if (this.patterns == null) {
      this.patterns = new ArrayList<>();
    }
    this.patterns.add(patternsItem);
    return this;
  }

  /**
   * Get patterns
   * @return patterns
   */
  @.annotation.Nonnull

  public [String] getPatterns() {
    return patterns;
  }


  public void setPatterns(@.annotation.Nonnull [String] patterns) {
    this.patterns = patterns;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceCallflowAddEditData serviceCallflowAddEditData = (ServiceCallflowAddEditData) o;
    return Objects.equals(this.featurecode, serviceCallflowAddEditData.featurecode) &&
        Objects.equals(this.flow, serviceCallflowAddEditData.flow) &&
        Objects.equals(this.name, serviceCallflowAddEditData.name) &&
        Objects.equals(this.numbers, serviceCallflowAddEditData.numbers) &&
        Objects.equals(this.patterns, serviceCallflowAddEditData.patterns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(featurecode, flow, name, numbers, patterns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceCallflowAddEditData {\n");
    sb.append("    featurecode: ").append(toIndentedString(featurecode)).append("\n");
    sb.append("    flow: ").append(toIndentedString(flow)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    numbers: ").append(toIndentedString(numbers)).append("\n");
    sb.append("    patterns: ").append(toIndentedString(patterns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

