/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceUpdateRecordTypeForAccount
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceUpdateRecordTypeForAccount {
  @.annotation.Nonnull
  private String recordType;

  public ServiceUpdateRecordTypeForAccount() {
  }

  public ServiceUpdateRecordTypeForAccount recordType(@.annotation.Nonnull String recordType) {
    
    this.recordType = recordType;
    return this;
  }

  /**
   * Get recordType
   * @return recordType
   */
  @.annotation.Nonnull

  public String getRecordType() {
    return recordType;
  }


  public void setRecordType(@.annotation.Nonnull String recordType) {
    this.recordType = recordType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceUpdateRecordTypeForAccount serviceUpdateRecordTypeForAccount = (ServiceUpdateRecordTypeForAccount) o;
    return Objects.equals(this.recordType, serviceUpdateRecordTypeForAccount.recordType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recordType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceUpdateRecordTypeForAccount {\n");
    sb.append("    recordType: ").append(toIndentedString(recordType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

