/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceAccountLimitOutput
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceAccountLimitOutput {
  @.annotation.Nullable
  private Number inboundTrunks;

  @.annotation.Nullable
  private Number outboundTrunks;

  @.annotation.Nullable
  private Number twowayTrunks;

  public ServiceAccountLimitOutput() {
  }

  public ServiceAccountLimitOutput inboundTrunks(@.annotation.Nullable Number inboundTrunks) {
    
    this.inboundTrunks = inboundTrunks;
    return this;
  }

  /**
   * Get inboundTrunks
   * @return inboundTrunks
   */
  @.annotation.Nullable

  public Number getInboundTrunks() {
    return inboundTrunks;
  }


  public void setInboundTrunks(@.annotation.Nullable Number inboundTrunks) {
    this.inboundTrunks = inboundTrunks;
  }

  public ServiceAccountLimitOutput outboundTrunks(@.annotation.Nullable Number outboundTrunks) {
    
    this.outboundTrunks = outboundTrunks;
    return this;
  }

  /**
   * Get outboundTrunks
   * @return outboundTrunks
   */
  @.annotation.Nullable

  public Number getOutboundTrunks() {
    return outboundTrunks;
  }


  public void setOutboundTrunks(@.annotation.Nullable Number outboundTrunks) {
    this.outboundTrunks = outboundTrunks;
  }

  public ServiceAccountLimitOutput twowayTrunks(@.annotation.Nullable Number twowayTrunks) {
    
    this.twowayTrunks = twowayTrunks;
    return this;
  }

  /**
   * Get twowayTrunks
   * @return twowayTrunks
   */
  @.annotation.Nullable

  public Number getTwowayTrunks() {
    return twowayTrunks;
  }


  public void setTwowayTrunks(@.annotation.Nullable Number twowayTrunks) {
    this.twowayTrunks = twowayTrunks;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceAccountLimitOutput serviceAccountLimitOutput = (ServiceAccountLimitOutput) o;
    return Objects.equals(this.inboundTrunks, serviceAccountLimitOutput.inboundTrunks) &&
        Objects.equals(this.outboundTrunks, serviceAccountLimitOutput.outboundTrunks) &&
        Objects.equals(this.twowayTrunks, serviceAccountLimitOutput.twowayTrunks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inboundTrunks, outboundTrunks, twowayTrunks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceAccountLimitOutput {\n");
    sb.append("    inboundTrunks: ").append(toIndentedString(inboundTrunks)).append("\n");
    sb.append("    outboundTrunks: ").append(toIndentedString(outboundTrunks)).append("\n");
    sb.append("    twowayTrunks: ").append(toIndentedString(twowayTrunks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

