/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ServiceVOIPAccountCallRecording from './ServiceVOIPAccountCallRecording';
import ServiceVOIPAccountMusicOnHold from './ServiceVOIPAccountMusicOnHold';
import ServiceVOIPSharedDoNotDisturb from './ServiceVOIPSharedDoNotDisturb';

/**
 * The ServiceVOIPAccountEditData model module.
 * @module model/ServiceVOIPAccountEditData
 * @version 1.1
 */
class ServiceVOIPAccountEditData {
    /**
     * Constructs a new <code>ServiceVOIPAccountEditData</code>.
     * @alias module:model/ServiceVOIPAccountEditData
     * @param name {String} 
     * @param timezone {String} 
     */
    constructor(name, timezone) { 
        
        ServiceVOIPAccountEditData.initialize(this, name, timezone);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, timezone) { 
        obj['name'] = name;
        obj['timezone'] = timezone;
    }

    /**
     * Constructs a <code>ServiceVOIPAccountEditData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ServiceVOIPAccountEditData} obj Optional instance to populate.
     * @return {module:model/ServiceVOIPAccountEditData} The populated <code>ServiceVOIPAccountEditData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServiceVOIPAccountEditData();

            if (data.hasOwnProperty('call_recording')) {
                obj['call_recording'] = ServiceVOIPAccountCallRecording.constructFromObject(data['call_recording']);
            }
            if (data.hasOwnProperty('do_not_disturb')) {
                obj['do_not_disturb'] = ServiceVOIPSharedDoNotDisturb.constructFromObject(data['do_not_disturb']);
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('music_on_hold')) {
                obj['music_on_hold'] = ServiceVOIPAccountMusicOnHold.constructFromObject(data['music_on_hold']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('timezone')) {
                obj['timezone'] = ApiClient.convertToType(data['timezone'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ServiceVOIPAccountEditData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ServiceVOIPAccountEditData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ServiceVOIPAccountEditData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `call_recording`
        if (data['call_recording']) { // data not null
          ServiceVOIPAccountCallRecording.validateJSON(data['call_recording']);
        }
        // validate the optional field `do_not_disturb`
        if (data['do_not_disturb']) { // data not null
          ServiceVOIPSharedDoNotDisturb.validateJSON(data['do_not_disturb']);
        }
        // validate the optional field `music_on_hold`
        if (data['music_on_hold']) { // data not null
          ServiceVOIPAccountMusicOnHold.validateJSON(data['music_on_hold']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['timezone'] && !(typeof data['timezone'] === 'string' || data['timezone'] instanceof String)) {
            throw new Error("Expected the field `timezone` to be a primitive type in the JSON string but got " + data['timezone']);
        }

        return true;
    }


}

ServiceVOIPAccountEditData.RequiredProperties = ["name", "timezone"];

/**
 * @member {module:model/ServiceVOIPAccountCallRecording} call_recording
 */
ServiceVOIPAccountEditData.prototype['call_recording'] = undefined;

/**
 * @member {module:model/ServiceVOIPSharedDoNotDisturb} do_not_disturb
 */
ServiceVOIPAccountEditData.prototype['do_not_disturb'] = undefined;

/**
 * @member {Boolean} enabled
 */
ServiceVOIPAccountEditData.prototype['enabled'] = undefined;

/**
 * @member {module:model/ServiceVOIPAccountMusicOnHold} music_on_hold
 */
ServiceVOIPAccountEditData.prototype['music_on_hold'] = undefined;

/**
 * @member {String} name
 */
ServiceVOIPAccountEditData.prototype['name'] = undefined;

/**
 * @member {String} timezone
 */
ServiceVOIPAccountEditData.prototype['timezone'] = undefined;






export default ServiceVOIPAccountEditData;

