/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceTelephoneNumberList
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceTelephoneNumberList {
  @.annotation.Nullable
  private [String] telephoneNumber;

  public ServiceTelephoneNumberList() {
  }

  public ServiceTelephoneNumberList telephoneNumber(@.annotation.Nullable [String] telephoneNumber) {
    
    this.telephoneNumber = telephoneNumber;
    return this;
  }

  public ServiceTelephoneNumberList addTelephoneNumberItem(String telephoneNumberItem) {
    if (this.telephoneNumber == null) {
      this.telephoneNumber = new ArrayList<>();
    }
    this.telephoneNumber.add(telephoneNumberItem);
    return this;
  }

  /**
   * Get telephoneNumber
   * @return telephoneNumber
   */
  @.annotation.Nullable

  public [String] getTelephoneNumber() {
    return telephoneNumber;
  }


  public void setTelephoneNumber(@.annotation.Nullable [String] telephoneNumber) {
    this.telephoneNumber = telephoneNumber;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceTelephoneNumberList serviceTelephoneNumberList = (ServiceTelephoneNumberList) o;
    return Objects.equals(this.telephoneNumber, serviceTelephoneNumberList.telephoneNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(telephoneNumber);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceTelephoneNumberList {\n");
    sb.append("    telephoneNumber: ").append(toIndentedString(telephoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

