/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;

/**
 * ServiceCallflowOutputShort
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceCallflowOutputShort {
  @.annotation.Nullable
  private String id;

  @.annotation.Nullable
  private [String] modules;

  @.annotation.Nullable
  private String name;

  @.annotation.Nullable
  private [String] numbers;

  @.annotation.Nullable
  private [String] patterns;

  public ServiceCallflowOutputShort() {
  }

  public ServiceCallflowOutputShort id(@.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @.annotation.Nullable

  public String getId() {
    return id;
  }


  public void setId(@.annotation.Nullable String id) {
    this.id = id;
  }

  public ServiceCallflowOutputShort modules(@.annotation.Nullable [String] modules) {
    
    this.modules = modules;
    return this;
  }

  public ServiceCallflowOutputShort addModulesItem(String modulesItem) {
    if (this.modules == null) {
      this.modules = new ArrayList<>();
    }
    this.modules.add(modulesItem);
    return this;
  }

  /**
   * Get modules
   * @return modules
   */
  @.annotation.Nullable

  public [String] getModules() {
    return modules;
  }


  public void setModules(@.annotation.Nullable [String] modules) {
    this.modules = modules;
  }

  public ServiceCallflowOutputShort name(@.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@.annotation.Nullable String name) {
    this.name = name;
  }

  public ServiceCallflowOutputShort numbers(@.annotation.Nullable [String] numbers) {
    
    this.numbers = numbers;
    return this;
  }

  public ServiceCallflowOutputShort addNumbersItem(String numbersItem) {
    if (this.numbers == null) {
      this.numbers = new ArrayList<>();
    }
    this.numbers.add(numbersItem);
    return this;
  }

  /**
   * Get numbers
   * @return numbers
   */
  @.annotation.Nullable

  public [String] getNumbers() {
    return numbers;
  }


  public void setNumbers(@.annotation.Nullable [String] numbers) {
    this.numbers = numbers;
  }

  public ServiceCallflowOutputShort patterns(@.annotation.Nullable [String] patterns) {
    
    this.patterns = patterns;
    return this;
  }

  public ServiceCallflowOutputShort addPatternsItem(String patternsItem) {
    if (this.patterns == null) {
      this.patterns = new ArrayList<>();
    }
    this.patterns.add(patternsItem);
    return this;
  }

  /**
   * Get patterns
   * @return patterns
   */
  @.annotation.Nullable

  public [String] getPatterns() {
    return patterns;
  }


  public void setPatterns(@.annotation.Nullable [String] patterns) {
    this.patterns = patterns;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceCallflowOutputShort serviceCallflowOutputShort = (ServiceCallflowOutputShort) o;
    return Objects.equals(this.id, serviceCallflowOutputShort.id) &&
        Objects.equals(this.modules, serviceCallflowOutputShort.modules) &&
        Objects.equals(this.name, serviceCallflowOutputShort.name) &&
        Objects.equals(this.numbers, serviceCallflowOutputShort.numbers) &&
        Objects.equals(this.patterns, serviceCallflowOutputShort.patterns);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, modules, name, numbers, patterns);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceCallflowOutputShort {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    modules: ").append(toIndentedString(modules)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    numbers: ").append(toIndentedString(numbers)).append("\n");
    sb.append("    patterns: ").append(toIndentedString(patterns)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

