/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import java.util.Objects;
import java.util.Arrays;
import ServiceCallForward;
import ServiceCallRecordingSettings;
import ServiceDeviceOutputFullCallerid;
import ServiceDeviceOutputFullSIP;
import ServiceMusicOnHold;
import ServiceVOIPSharedDoNotDisturb;

/**
 * ServiceDeviceOutputFull
 */
@.annotation.Generated(value = "org.openapitools.codegen.languages.JavascriptClientCodegen", comments = "Generator version: 7.11.0-SNAPSHOT")
public class ServiceDeviceOutputFull {
  @.annotation.Nullable
  private ServiceCallForward callForward;

  @.annotation.Nullable
  private ServiceCallRecordingSettings callRecording;

  @.annotation.Nullable
  private ServiceDeviceOutputFullCallerid callerId;

  @.annotation.Nullable
  private String deviceType;

  @.annotation.Nullable
  private ServiceVOIPSharedDoNotDisturb doNotDisturb;

  @.annotation.Nullable
  private Boolean enabled;

  @.annotation.Nullable
  private String id;

  @.annotation.Nullable
  private String macAddress;

  @.annotation.Nullable
  private ServiceMusicOnHold musicOnHold;

  @.annotation.Nullable
  private String name;

  @.annotation.Nullable
  private String ownerId;

  @.annotation.Nullable
  private ServiceDeviceOutputFullSIP sip;

  public ServiceDeviceOutputFull() {
  }

  public ServiceDeviceOutputFull callForward(@.annotation.Nullable ServiceCallForward callForward) {
    
    this.callForward = callForward;
    return this;
  }

  /**
   * Get callForward
   * @return callForward
   */
  @.annotation.Nullable

  public ServiceCallForward getCallForward() {
    return callForward;
  }


  public void setCallForward(@.annotation.Nullable ServiceCallForward callForward) {
    this.callForward = callForward;
  }

  public ServiceDeviceOutputFull callRecording(@.annotation.Nullable ServiceCallRecordingSettings callRecording) {
    
    this.callRecording = callRecording;
    return this;
  }

  /**
   * Get callRecording
   * @return callRecording
   */
  @.annotation.Nullable

  public ServiceCallRecordingSettings getCallRecording() {
    return callRecording;
  }


  public void setCallRecording(@.annotation.Nullable ServiceCallRecordingSettings callRecording) {
    this.callRecording = callRecording;
  }

  public ServiceDeviceOutputFull callerId(@.annotation.Nullable ServiceDeviceOutputFullCallerid callerId) {
    
    this.callerId = callerId;
    return this;
  }

  /**
   * Get callerId
   * @return callerId
   */
  @.annotation.Nullable

  public ServiceDeviceOutputFullCallerid getCallerId() {
    return callerId;
  }


  public void setCallerId(@.annotation.Nullable ServiceDeviceOutputFullCallerid callerId) {
    this.callerId = callerId;
  }

  public ServiceDeviceOutputFull deviceType(@.annotation.Nullable String deviceType) {
    
    this.deviceType = deviceType;
    return this;
  }

  /**
   * Get deviceType
   * @return deviceType
   */
  @.annotation.Nullable

  public String getDeviceType() {
    return deviceType;
  }


  public void setDeviceType(@.annotation.Nullable String deviceType) {
    this.deviceType = deviceType;
  }

  public ServiceDeviceOutputFull doNotDisturb(@.annotation.Nullable ServiceVOIPSharedDoNotDisturb doNotDisturb) {
    
    this.doNotDisturb = doNotDisturb;
    return this;
  }

  /**
   * Get doNotDisturb
   * @return doNotDisturb
   */
  @.annotation.Nullable

  public ServiceVOIPSharedDoNotDisturb getDoNotDisturb() {
    return doNotDisturb;
  }


  public void setDoNotDisturb(@.annotation.Nullable ServiceVOIPSharedDoNotDisturb doNotDisturb) {
    this.doNotDisturb = doNotDisturb;
  }

  public ServiceDeviceOutputFull enabled(@.annotation.Nullable Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

  /**
   * Get enabled
   * @return enabled
   */
  @.annotation.Nullable

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(@.annotation.Nullable Boolean enabled) {
    this.enabled = enabled;
  }

  public ServiceDeviceOutputFull id(@.annotation.Nullable String id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @.annotation.Nullable

  public String getId() {
    return id;
  }


  public void setId(@.annotation.Nullable String id) {
    this.id = id;
  }

  public ServiceDeviceOutputFull macAddress(@.annotation.Nullable String macAddress) {
    
    this.macAddress = macAddress;
    return this;
  }

  /**
   * Get macAddress
   * @return macAddress
   */
  @.annotation.Nullable

  public String getMacAddress() {
    return macAddress;
  }


  public void setMacAddress(@.annotation.Nullable String macAddress) {
    this.macAddress = macAddress;
  }

  public ServiceDeviceOutputFull musicOnHold(@.annotation.Nullable ServiceMusicOnHold musicOnHold) {
    
    this.musicOnHold = musicOnHold;
    return this;
  }

  /**
   * Provision  *DeviceOutputFullProvision &#x60;json:\&quot;provision\&quot;&#x60;
   * @return musicOnHold
   */
  @.annotation.Nullable

  public ServiceMusicOnHold getMusicOnHold() {
    return musicOnHold;
  }


  public void setMusicOnHold(@.annotation.Nullable ServiceMusicOnHold musicOnHold) {
    this.musicOnHold = musicOnHold;
  }

  public ServiceDeviceOutputFull name(@.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @.annotation.Nullable

  public String getName() {
    return name;
  }


  public void setName(@.annotation.Nullable String name) {
    this.name = name;
  }

  public ServiceDeviceOutputFull ownerId(@.annotation.Nullable String ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   */
  @.annotation.Nullable

  public String getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(@.annotation.Nullable String ownerId) {
    this.ownerId = ownerId;
  }

  public ServiceDeviceOutputFull sip(@.annotation.Nullable ServiceDeviceOutputFullSIP sip) {
    
    this.sip = sip;
    return this;
  }

  /**
   * Get sip
   * @return sip
   */
  @.annotation.Nullable

  public ServiceDeviceOutputFullSIP getSip() {
    return sip;
  }


  public void setSip(@.annotation.Nullable ServiceDeviceOutputFullSIP sip) {
    this.sip = sip;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceDeviceOutputFull serviceDeviceOutputFull = (ServiceDeviceOutputFull) o;
    return Objects.equals(this.callForward, serviceDeviceOutputFull.callForward) &&
        Objects.equals(this.callRecording, serviceDeviceOutputFull.callRecording) &&
        Objects.equals(this.callerId, serviceDeviceOutputFull.callerId) &&
        Objects.equals(this.deviceType, serviceDeviceOutputFull.deviceType) &&
        Objects.equals(this.doNotDisturb, serviceDeviceOutputFull.doNotDisturb) &&
        Objects.equals(this.enabled, serviceDeviceOutputFull.enabled) &&
        Objects.equals(this.id, serviceDeviceOutputFull.id) &&
        Objects.equals(this.macAddress, serviceDeviceOutputFull.macAddress) &&
        Objects.equals(this.musicOnHold, serviceDeviceOutputFull.musicOnHold) &&
        Objects.equals(this.name, serviceDeviceOutputFull.name) &&
        Objects.equals(this.ownerId, serviceDeviceOutputFull.ownerId) &&
        Objects.equals(this.sip, serviceDeviceOutputFull.sip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callForward, callRecording, callerId, deviceType, doNotDisturb, enabled, id, macAddress, musicOnHold, name, ownerId, sip);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceDeviceOutputFull {\n");
    sb.append("    callForward: ").append(toIndentedString(callForward)).append("\n");
    sb.append("    callRecording: ").append(toIndentedString(callRecording)).append("\n");
    sb.append("    callerId: ").append(toIndentedString(callerId)).append("\n");
    sb.append("    deviceType: ").append(toIndentedString(deviceType)).append("\n");
    sb.append("    doNotDisturb: ").append(toIndentedString(doNotDisturb)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    macAddress: ").append(toIndentedString(macAddress)).append("\n");
    sb.append("    musicOnHold: ").append(toIndentedString(musicOnHold)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    sip: ").append(toIndentedString(sip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

