/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceTTS;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPMediaAddEditData
 */
class ServiceVOIPMediaAddEditDataTest {
    private final ServiceVOIPMediaAddEditData model = new ServiceVOIPMediaAddEditData();

    /**
     * Model tests for ServiceVOIPMediaAddEditData
     */
    @Test
    void testServiceVOIPMediaAddEditData() {
        // TODO: test ServiceVOIPMediaAddEditData
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'mediaSource'
     */
    @Test
    void mediaSourceTest() {
        // TODO: test mediaSource
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'tts'
     */
    @Test
    void ttsTest() {
        // TODO: test tts
    }

}
