/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceEndpoint;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPGroupAddEdit2
 */
class ServiceVOIPGroupAddEdit2Test {
    private final ServiceVOIPGroupAddEdit2 model = new ServiceVOIPGroupAddEdit2();

    /**
     * Model tests for ServiceVOIPGroupAddEdit2
     */
    @Test
    void testServiceVOIPGroupAddEdit2() {
        // TODO: test ServiceVOIPGroupAddEdit2
    }

    /**
     * Test the property 'endpoints'
     */
    @Test
    void endpointsTest() {
        // TODO: test endpoints
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
