/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPCallQueueRecipientLoginLogoutData
 */
class ServiceVOIPCallQueueRecipientLoginLogoutDataTest {
    private final ServiceVOIPCallQueueRecipientLoginLogoutData model = new ServiceVOIPCallQueueRecipientLoginLogoutData();

    /**
     * Model tests for ServiceVOIPCallQueueRecipientLoginLogoutData
     */
    @Test
    void testServiceVOIPCallQueueRecipientLoginLogoutData() {
        // TODO: test ServiceVOIPCallQueueRecipientLoginLogoutData
    }

    /**
     * Test the property 'action'
     */
    @Test
    void actionTest() {
        // TODO: test action
    }

}
