/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceTemporalRuleOutputFull
 */
class ServiceTemporalRuleOutputFullTest {
    private final ServiceTemporalRuleOutputFull model = new ServiceTemporalRuleOutputFull();

    /**
     * Model tests for ServiceTemporalRuleOutputFull
     */
    @Test
    void testServiceTemporalRuleOutputFull() {
        // TODO: test ServiceTemporalRuleOutputFull
    }

    /**
     * Test the property 'cycle'
     */
    @Test
    void cycleTest() {
        // TODO: test cycle
    }

    /**
     * Test the property 'days'
     */
    @Test
    void daysTest() {
        // TODO: test days
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'interval'
     */
    @Test
    void intervalTest() {
        // TODO: test interval
    }

    /**
     * Test the property 'month'
     */
    @Test
    void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ordinal'
     */
    @Test
    void ordinalTest() {
        // TODO: test ordinal
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'timeWindowStart'
     */
    @Test
    void timeWindowStartTest() {
        // TODO: test timeWindowStart
    }

    /**
     * Test the property 'timeWindowStop'
     */
    @Test
    void timeWindowStopTest() {
        // TODO: test timeWindowStop
    }

    /**
     * Test the property 'wdays'
     */
    @Test
    void wdaysTest() {
        // TODO: test wdays
    }

}
