/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhiteLabelCommunicationsCPaasApiDocumentation);
  }
}(this, function(expect, WhiteLabelCommunicationsCPaasApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceCallQueueOutputFull', function() {
    it('should create an instance of ServiceCallQueueOutputFull', function() {
      // uncomment below and update the code to test ServiceCallQueueOutputFull
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be.a(WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull);
    });

    it('should have the property agentWrapupTime (base name: "agent_wrapup_time")', function() {
      // uncomment below and update the code to test the property agentWrapupTime
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property features (base name: "features")', function() {
      // uncomment below and update the code to test the property features
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property forceAwayOnReject (base name: "force_away_on_reject")', function() {
      // uncomment below and update the code to test the property forceAwayOnReject
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property queueRouter (base name: "queue_router")', function() {
      // uncomment below and update the code to test the property queueRouter
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property queueType (base name: "queue_type")', function() {
      // uncomment below and update the code to test the property queueType
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property ringTimeout (base name: "ring_timeout")', function() {
      // uncomment below and update the code to test the property ringTimeout
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

    it('should have the property tickTime (base name: "tick_time")', function() {
      // uncomment below and update the code to test the property tickTime
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceCallQueueOutputFull();
      //expect(instance).to.be();
    });

  });

}));
