/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceSystemStatusSupportService
 */
class ServiceSystemStatusSupportServiceTest {
    private final ServiceSystemStatusSupportService model = new ServiceSystemStatusSupportService();

    /**
     * Model tests for ServiceSystemStatusSupportService
     */
    @Test
    void testServiceSystemStatusSupportService() {
        // TODO: test ServiceSystemStatusSupportService
    }

    /**
     * Test the property 'e911Server'
     */
    @Test
    void e911ServerTest() {
        // TODO: test e911Server
    }

    /**
     * Test the property 'phoneNumberServer'
     */
    @Test
    void phoneNumberServerTest() {
        // TODO: test phoneNumberServer
    }

}
