/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceE911ActiveLocationStatus;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceE911ActiveLocationOutput
 */
class ServiceE911ActiveLocationOutputTest {
    private final ServiceE911ActiveLocationOutput model = new ServiceE911ActiveLocationOutput();

    /**
     * Model tests for ServiceE911ActiveLocationOutput
     */
    @Test
    void testServiceE911ActiveLocationOutput() {
        // TODO: test ServiceE911ActiveLocationOutput
    }

    /**
     * Test the property 'locationStatus'
     */
    @Test
    void locationStatusTest() {
        // TODO: test locationStatus
    }

}
