/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceCallQueueRolesOutput
 */
class ServiceCallQueueRolesOutputTest {
    private final ServiceCallQueueRolesOutput model = new ServiceCallQueueRolesOutput();

    /**
     * Model tests for ServiceCallQueueRolesOutput
     */
    @Test
    void testServiceCallQueueRolesOutput() {
        // TODO: test ServiceCallQueueRolesOutput
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
