/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceMetaflowPattern;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceMetaflowOutput
 */
class ServiceMetaflowOutputTest {
    private final ServiceMetaflowOutput model = new ServiceMetaflowOutput();

    /**
     * Model tests for ServiceMetaflowOutput
     */
    @Test
    void testServiceMetaflowOutput() {
        // TODO: test ServiceMetaflowOutput
    }

    /**
     * Test the property 'bindingDigit'
     */
    @Test
    void bindingDigitTest() {
        // TODO: test bindingDigit
    }

    /**
     * Test the property 'numbers'
     */
    @Test
    void numbersTest() {
        // TODO: test numbers
    }

    /**
     * Test the property 'patterns'
     */
    @Test
    void patternsTest() {
        // TODO: test patterns
    }

}
