/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhiteLabelCommunicationsCPaasApiDocumentation);
  }
}(this, function(expect, WhiteLabelCommunicationsCPaasApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceE911LocationURILegacyData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ServiceE911LocationURILegacyData', function() {
    it('should create an instance of ServiceE911LocationURILegacyData', function() {
      // uncomment below and update the code to test ServiceE911LocationURILegacyData
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceE911LocationURILegacyData();
      //expect(instance).to.be.a(WhiteLabelCommunicationsCPaasApiDocumentation.ServiceE911LocationURILegacyData);
    });

    it('should have the property houseNumber (base name: "houseNumber")', function() {
      // uncomment below and update the code to test the property houseNumber
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceE911LocationURILegacyData();
      //expect(instance).to.be();
    });

    it('should have the property predirectional (base name: "predirectional")', function() {
      // uncomment below and update the code to test the property predirectional
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceE911LocationURILegacyData();
      //expect(instance).to.be();
    });

    it('should have the property streetName (base name: "streetName")', function() {
      // uncomment below and update the code to test the property streetName
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceE911LocationURILegacyData();
      //expect(instance).to.be();
    });

    it('should have the property suite (base name: "suite")', function() {
      // uncomment below and update the code to test the property suite
      //var instance = new WhiteLabelCommunicationsCPaasApiDocumentation.ServiceE911LocationURILegacyData();
      //expect(instance).to.be();
    });

  });

}));
