/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceTemporalRuleSetOutputShort;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceDocsTemporalRuleSetGetAll
 */
class ServiceDocsTemporalRuleSetGetAllTest {
    private final ServiceDocsTemporalRuleSetGetAll model = new ServiceDocsTemporalRuleSetGetAll();

    /**
     * Model tests for ServiceDocsTemporalRuleSetGetAll
     */
    @Test
    void testServiceDocsTemporalRuleSetGetAll() {
        // TODO: test ServiceDocsTemporalRuleSetGetAll
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'nextStartKey'
     */
    @Test
    void nextStartKeyTest() {
        // TODO: test nextStartKey
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'startKey'
     */
    @Test
    void startKeyTest() {
        // TODO: test startKey
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    void statusCodeTest() {
        // TODO: test statusCode
    }

}
