/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceCallQueueStatusStats;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceCallQueueStatusOutput
 */
class ServiceCallQueueStatusOutputTest {
    private final ServiceCallQueueStatusOutput model = new ServiceCallQueueStatusOutput();

    /**
     * Model tests for ServiceCallQueueStatusOutput
     */
    @Test
    void testServiceCallQueueStatusOutput() {
        // TODO: test ServiceCallQueueStatusOutput
    }

    /**
     * Test the property 'activeRecipientCount'
     */
    @Test
    void activeRecipientCountTest() {
        // TODO: test activeRecipientCount
    }

    /**
     * Test the property 'availableRecipientCount'
     */
    @Test
    void availableRecipientCountTest() {
        // TODO: test availableRecipientCount
    }

    /**
     * Test the property 'node'
     */
    @Test
    void nodeTest() {
        // TODO: test node
    }

    /**
     * Test the property 'stats'
     */
    @Test
    void statsTest() {
        // TODO: test stats
    }

}
