/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceCampaignTagDetagPhonenumbersOutput
 */
class ServiceCampaignTagDetagPhonenumbersOutputTest {
    private final ServiceCampaignTagDetagPhonenumbersOutput model = new ServiceCampaignTagDetagPhonenumbersOutput();

    /**
     * Model tests for ServiceCampaignTagDetagPhonenumbersOutput
     */
    @Test
    void testServiceCampaignTagDetagPhonenumbersOutput() {
        // TODO: test ServiceCampaignTagDetagPhonenumbersOutput
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'orderStatus'
     */
    @Test
    void orderStatusTest() {
        // TODO: test orderStatus
    }

}
