/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceCallForward;
import ServiceCallRecordingSettings;
import ServiceMusicOnHold;
import ServiceVOIPSharedDoNotDisturb;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceUserOutputFull
 */
class ServiceUserOutputFullTest {
    private final ServiceUserOutputFull model = new ServiceUserOutputFull();

    /**
     * Model tests for ServiceUserOutputFull
     */
    @Test
    void testServiceUserOutputFull() {
        // TODO: test ServiceUserOutputFull
    }

    /**
     * Test the property 'callForward'
     */
    @Test
    void callForwardTest() {
        // TODO: test callForward
    }

    /**
     * Test the property 'callRecording'
     */
    @Test
    void callRecordingTest() {
        // TODO: test callRecording
    }

    /**
     * Test the property 'doNotDisturb'
     */
    @Test
    void doNotDisturbTest() {
        // TODO: test doNotDisturb
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'musicOnHold'
     */
    @Test
    void musicOnHoldTest() {
        // TODO: test musicOnHold
    }

    /**
     * Test the property 'presenceId'
     */
    @Test
    void presenceIdTest() {
        // TODO: test presenceId
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'verified'
     */
    @Test
    void verifiedTest() {
        // TODO: test verified
    }

}
