/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPVoicemailMessageChange
 */
class ServiceVOIPVoicemailMessageChangeTest {
    private final ServiceVOIPVoicemailMessageChange model = new ServiceVOIPVoicemailMessageChange();

    /**
     * Model tests for ServiceVOIPVoicemailMessageChange
     */
    @Test
    void testServiceVOIPVoicemailMessageChange() {
        // TODO: test ServiceVOIPVoicemailMessageChange
    }

    /**
     * Test the property 'folder'
     */
    @Test
    void folderTest() {
        // TODO: test folder
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    void sourceIdTest() {
        // TODO: test sourceId
    }

}
