/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServicePhoneNumberSearchOutput;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceDocsPhonenumberSearchGetAll
 */
class ServiceDocsPhonenumberSearchGetAllTest {
    private final ServiceDocsPhonenumberSearchGetAll model = new ServiceDocsPhonenumberSearchGetAll();

    /**
     * Model tests for ServiceDocsPhonenumberSearchGetAll
     */
    @Test
    void testServiceDocsPhonenumberSearchGetAll() {
        // TODO: test ServiceDocsPhonenumberSearchGetAll
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    void statusCodeTest() {
        // TODO: test statusCode
    }

}
