/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceE911LocationOutput;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceE911AddLocationOutput
 */
class ServiceE911AddLocationOutputTest {
    private final ServiceE911AddLocationOutput model = new ServiceE911AddLocationOutput();

    /**
     * Model tests for ServiceE911AddLocationOutput
     */
    @Test
    void testServiceE911AddLocationOutput() {
        // TODO: test ServiceE911AddLocationOutput
    }

    /**
     * Test the property 'location'
     */
    @Test
    void locationTest() {
        // TODO: test location
    }

}
