/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceEndpoint;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceGroupOutputFull
 */
class ServiceGroupOutputFullTest {
    private final ServiceGroupOutputFull model = new ServiceGroupOutputFull();

    /**
     * Model tests for ServiceGroupOutputFull
     */
    @Test
    void testServiceGroupOutputFull() {
        // TODO: test ServiceGroupOutputFull
    }

    /**
     * Test the property 'endpoints'
     */
    @Test
    void endpointsTest() {
        // TODO: test endpoints
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

}
