/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import ServiceStoragePlan;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPStorageAddEditData
 */
class ServiceVOIPStorageAddEditDataTest {
    private final ServiceVOIPStorageAddEditData model = new ServiceVOIPStorageAddEditData();

    /**
     * Model tests for ServiceVOIPStorageAddEditData
     */
    @Test
    void testServiceVOIPStorageAddEditData() {
        // TODO: test ServiceVOIPStorageAddEditData
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'connections'
     */
    @Test
    void connectionsTest() {
        // TODO: test connections
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'plan'
     */
    @Test
    void planTest() {
        // TODO: test plan
    }

}
