/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package model;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ServiceVOIPPresenceSetResetEditData
 */
class ServiceVOIPPresenceSetResetEditDataTest {
    private final ServiceVOIPPresenceSetResetEditData model = new ServiceVOIPPresenceSetResetEditData();

    /**
     * Model tests for ServiceVOIPPresenceSetResetEditData
     */
    @Test
    void testServiceVOIPPresenceSetResetEditData() {
        // TODO: test ServiceVOIPPresenceSetResetEditData
    }

    /**
     * Test the property 'action'
     */
    @Test
    void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

}
