/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhiteLabelCommunicationsCPaasApiDocumentation);
  }
}(this, function(expect, WhiteLabelCommunicationsCPaasApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WhiteLabelCommunicationsCPaasApiDocumentation.CallflowApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CallflowApi', function() {
    describe('v1AccountAccountIDCallflowCallflowIDDelete', function() {
      it('should call v1AccountAccountIDCallflowCallflowIDDelete successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDCallflowCallflowIDDelete
        //instance.v1AccountAccountIDCallflowCallflowIDDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDCallflowCallflowIDGet', function() {
      it('should call v1AccountAccountIDCallflowCallflowIDGet successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDCallflowCallflowIDGet
        //instance.v1AccountAccountIDCallflowCallflowIDGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDCallflowCallflowIDPut', function() {
      it('should call v1AccountAccountIDCallflowCallflowIDPut successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDCallflowCallflowIDPut
        //instance.v1AccountAccountIDCallflowCallflowIDPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDCallflowGet', function() {
      it('should call v1AccountAccountIDCallflowGet successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDCallflowGet
        //instance.v1AccountAccountIDCallflowGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDCallflowPost', function() {
      it('should call v1AccountAccountIDCallflowPost successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDCallflowPost
        //instance.v1AccountAccountIDCallflowPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
