/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api;

import .ApiException;
import ServiceAPIResponse;
import ServiceDocsCallQueueGetAll;
import ServiceDocsCallQueueGetRoles;
import ServiceDocsCallQueueGetSingle;
import ServiceDocsCallQueueGetSingleStatus;
import ServiceVOIPCallQueueAddEditData;
import ServiceVOIPCallQueueRoleAssignData;
import UtilCPAASError;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CallQueueManagementApi
 */
class CallQueueManagementApiTest {

    private final CallQueueManagementApi api = new CallQueueManagementApi();

    /**
     * Get Call Queues
     *
     * Retrieve call queue details for an account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDCallqueueGetTest() throws ApiException {
        //
        //String accountID = null;
        //
        //ServiceDocsCallQueueGetAll response = api.v1AccountAccountIDCallqueueGet(accountID);

        // TODO: test validations
    }
    /**
     * Create Call Queue
     *
     * Set up a call queue in an account for specific inbound calls.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDCallqueuePostTest() throws ApiException {
        //
        //String accountID = null;
        //
        //ServiceVOIPCallQueueAddEditData reqBody = null;
        //
        //ServiceDocsCallQueueGetSingle response = api.v1AccountAccountIDCallqueuePost(accountID, reqBody);

        // TODO: test validations
    }
    /**
     * Delete Call Queue
     *
     * Remove the call queue from an account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDCallqueueQueueIDDeleteTest() throws ApiException {
        //
        //String accountID = null;
        //
        //String queueID = null;
        //
        //ServiceDocsCallQueueGetSingle response = api.v1AccountAccountIDCallqueueQueueIDDelete(accountID, queueID);

        // TODO: test validations
    }
    /**
     * Get Call Queue Details
     *
     * Capture metadata about a specific queue, such as queue_type and agent_wrapup_time.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDCallqueueQueueIDGetTest() throws ApiException {
        //
        //String accountID = null;
        //
        //String queueID = null;
        //
        //ServiceDocsCallQueueGetSingle response = api.v1AccountAccountIDCallqueueQueueIDGet(accountID, queueID);

        // TODO: test validations
    }
    /**
     * Update Call Queue
     *
     * Update the metadata mentioned above.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDCallqueueQueueIDPutTest() throws ApiException {
        //
        //String accountID = null;
        //
        //String queueID = null;
        //
        //ServiceVOIPCallQueueAddEditData reqBody = null;
        //
        //ServiceDocsCallQueueGetSingle response = api.v1AccountAccountIDCallqueueQueueIDPut(accountID, queueID, reqBody);

        // TODO: test validations
    }
    /**
     * Get Call Queue Status
     *
     * Access the status of a call queue in an account, such as the number of available agents (recipients), estimated wait time, and number of active sessions.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDCallqueueQueueIDStatusGetTest() throws ApiException {
        //
        //String accountID = null;
        //
        //String queueID = null;
        //
        //ServiceDocsCallQueueGetSingleStatus response = api.v1AccountAccountIDCallqueueQueueIDStatusGet(accountID, queueID);

        // TODO: test validations
    }
    /**
     * Get Queue Roles of Account
     *
     * Obtain data about each queue role in an account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDQueuerolesGetTest() throws ApiException {
        //
        //String accountID = null;
        //
        //ServiceDocsCallQueueGetRoles response = api.v1AccountAccountIDQueuerolesGet(accountID);

        // TODO: test validations
    }
    /**
     * Assign Queue Role to Call Queue
     *
     * Assign roles to members in a call queue.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountIDQueuerolesQueueIDPostTest() throws ApiException {
        //
        //String accountID = null;
        //
        //String queueID = null;
        //
        //ServiceVOIPCallQueueRoleAssignData reqBody = null;
        //
        //ServiceAPIResponse response = api.v1AccountAccountIDQueuerolesQueueIDPost(accountID, queueID, reqBody);

        // TODO: test validations
    }
}
