/*
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package api;

import .ApiException;
import ServiceAPIResponseStatusCodeOnly;
import ServiceDocsAccountPhonenumberGetAll;
import ServiceDocsOrderPhonenumber;
import ServiceDocsPhonenumberAssignPayload;
import ServiceDocsPhonenumberSearchGetAll;
import ServiceDocsPhonenumberUnassignPayload;
import ServiceTelephoneNumberList;
import UtilCPAASError;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PhoneNumberApi
 */
class PhoneNumberApiTest {

    private final PhoneNumberApi api = new PhoneNumberApi();

    /**
     * Get Assigned Numbers List
     *
     * Access all phone numbers assigned to a CPaaS account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountAccountidPhonenumberGetTest() throws ApiException {
        //
        //String accountid = null;
        //
        //String startKey = null;
        //
        //Number pageSize = null;
        //
        //ServiceDocsAccountPhonenumberGetAll response = api.v1AccountAccountidPhonenumberGet(accountid, startKey, pageSize);

        // TODO: test validations
    }
    /**
     * Assign Number
     *
     * Assign a purchased phone number to an account.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountPhonenumberAssignPostTest() throws ApiException {
        //
        //ServiceDocsPhonenumberAssignPayload payload = null;
        //
        //ServiceAPIResponseStatusCodeOnly response = api.v1AccountPhonenumberAssignPost(payload);

        // TODO: test validations
    }
    /**
     * Disconnect Number
     *
     * Disconnecting a phone number from a CPaaS account relinquishes ownership of the number back to the carrier.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountPhonenumberDisconnectPostTest() throws ApiException {
        //
        //ServiceDocsPhonenumberUnassignPayload payload = null;
        //
        //ServiceAPIResponseStatusCodeOnly response = api.v1AccountPhonenumberDisconnectPost(payload);

        // TODO: test validations
    }
    /**
     * Get Unassigned Numbers List
     *
     * Obtain all phone numbers that have not been assigned to a CPaaS account within your organization.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountPhonenumberGetTest() throws ApiException {
        //
        //String startKey = null;
        //
        //Number pageSize = null;
        //
        //ServiceDocsAccountPhonenumberGetAll response = api.v1AccountPhonenumberGet(startKey, pageSize);

        // TODO: test validations
    }
    /**
     * Purchase Number
     *
     * Purchase or activate a phone number for CPaaS accounts within your business.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountPhonenumberPostTest() throws ApiException {
        //
        //ServiceTelephoneNumberList phonenumber = null;
        //
        //ServiceDocsOrderPhonenumber response = api.v1AccountPhonenumberPost(phonenumber);

        // TODO: test validations
    }
    /**
     * Unassign Number
     *
     * Remove a phone number from an account and place it back on the list of unassigned phone numbers.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1AccountPhonenumberUnassignPostTest() throws ApiException {
        //
        //ServiceDocsPhonenumberUnassignPayload payload = null;
        //
        //ServiceAPIResponseStatusCodeOnly response = api.v1AccountPhonenumberUnassignPost(payload);

        // TODO: test validations
    }
    /**
     * Search New Numbers
     *
     * Conduct a search for available phone numbers for purchase within an area code.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    void v1PhonenumberSearchGetTest() throws ApiException {
        //
        //String areaCode = null;
        //
        //Number quantity = null;
        //
        //ServiceDocsPhonenumberSearchGetAll response = api.v1PhonenumberSearchGet(areaCode, quantity);

        // TODO: test validations
    }
}
