/**
 * White Label Communications CPaas API Documentation
 * A CPaaS platform API
 *
 * The version of the OpenAPI document: 1.1
 * Contact: support@whitelabelcomm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.WhiteLabelCommunicationsCPaasApiDocumentation);
  }
}(this, function(expect, WhiteLabelCommunicationsCPaasApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new WhiteLabelCommunicationsCPaasApiDocumentation.TemporalRuleApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TemporalRuleApi', function() {
    describe('v1AccountAccountIDTemporalruleGet', function() {
      it('should call v1AccountAccountIDTemporalruleGet successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDTemporalruleGet
        //instance.v1AccountAccountIDTemporalruleGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDTemporalrulePost', function() {
      it('should call v1AccountAccountIDTemporalrulePost successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDTemporalrulePost
        //instance.v1AccountAccountIDTemporalrulePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDTemporalruleTemporalRuleIDDelete', function() {
      it('should call v1AccountAccountIDTemporalruleTemporalRuleIDDelete successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDTemporalruleTemporalRuleIDDelete
        //instance.v1AccountAccountIDTemporalruleTemporalRuleIDDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDTemporalruleTemporalRuleIDGet', function() {
      it('should call v1AccountAccountIDTemporalruleTemporalRuleIDGet successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDTemporalruleTemporalRuleIDGet
        //instance.v1AccountAccountIDTemporalruleTemporalRuleIDGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v1AccountAccountIDTemporalruleTemporalRuleIDPut', function() {
      it('should call v1AccountAccountIDTemporalruleTemporalRuleIDPut successfully', function(done) {
        //uncomment below and update the code to test v1AccountAccountIDTemporalruleTemporalRuleIDPut
        //instance.v1AccountAccountIDTemporalruleTemporalRuleIDPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
